export const Data = [
    {
        "Id": 1,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 2,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 3,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 4,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 5,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 6,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 7,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 8,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 9,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 10,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 11,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 12,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 13,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 14,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 15,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 16,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 17,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 18,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 19,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 20,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 21,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 22,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 23,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 24,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 25,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 26,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 27,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    },
    {
        "Id": 28,
        "DivName": "Abc",
        "DivisionID": 1,
        "IsAddNewItem": true,
        "IsImportItems": false,
        "IsImportGroups": true,
        "IsUpdateItem": true,
        "IsCItemId": true,
        "IsItemName": true,
        "IsSalesModify": true,
        "IsSalesDelete": false,
        "IsUnitModify": true,
        "IsShowVoucherButton": true,
        "IsGiveSweetPOSUpdate": false,
        "IsSweetPOSAutoUpdate": true,
        "IsSweetPOSServiceAutoUpdate": true,
        "IsEayBillUploadExist": false
    }
]