export const POST_BOM = 'POST_BOM'
export const POST_BOM_SUCCESS = 'POST_BOM_SUCCESS'

export const GET_ITEM_UNITS_DROPDOWN_API = 'GET_ITEM_UNITS_DROPDOWN_API'
export const GET_ITEM_UNITS_DROPDOWN_API_SUCCESS = 'GET_ITEM_UNITS_DROPDOWN_API_SUCCESS'

export const GET_BOM_LIST_PAGE='GET_BOM_LIST_PAGE'
export const GET_BOM_LIST_PAGE_SUCCESS='GET_BOM_LIST_PAGE_SUCCESS'

export const EDIT_BOM_LIST_ID='EDIT_BOM_LIST_ID'
export const EDIT_BOM_LIST_ID_SUCCESS='EDIT_BOM_LIST_ID_SUCCESS'

