export const POST_BOM = 'POST_BOM'
export const POST_BOM_SUCCESS = 'POST_BOM_SUCCESS'

export const GET_ITEM_UNITS_DROPDOWN_API = 'GET_ITEM_UNITS_DROPDOWN_API'
export const GET_ITEM_UNITS_DROPDOWN_API_SUCCESS = 'GET_ITEM_UNITS_DROPDOWN_API_SUCCESS'



