export const GET_CHALLAN_LIST_PAGE = 'GET_CHALLAN_LIST_PAGE'
export const GET_CHALLAN_LIST_PAGE_SUCCESS = 'GET_CHALLAN_LIST_PAGE_SUCCESS'

export const CHALLAN_LIST_FILTERS = 'CHALLAN_LIST_FILTERS'

export const INWARD_BUTTON_ID = 'INWARD_BUTTON_ID'
export const INWARD_BUTTON_ID_SUCCESS = 'INWARD_BUTTON_ID_SUCCESS'