
const isParentLength = 3
const isRowLength = 56

function innerdataFunc(index) {
    return {
        Item: index,
        ItemName: "Refined Grounut Oil",
        Quantity: "11.000",
        MRP: null,
        MRPValue: null,
        Rate: "3000.00",
        TaxType: "GST",
        UnitName: "Liter",
        BaseUnitQuantity: "14005.000",
        GST: 106,
        GSTPercentage: "5.00",
        MarginValue: null,
        BasicAmount: "33000.00",
        GSTAmount: "1650.00",
        CGST: "825.00",
        SGST: "825.00",
        IGST: "0.00",
        CGSTPercentage: "2.50",
        SGSTPercentage: "2.50",
        IGSTPercentage: "0.00",
        Amount: "34650.00",
        BatchCode: "A10",
        BatchDate: "2023-02-25"
    }
}

function outerdatfunc(index) {
    const parentData = {
        id: 70,
        InvoiceDate: "2023-02-27",
        InvoiceNumber: 3,
        FullInvoiceNumber: "IN 3",
        GrandTotal: "35573.00",
        RoundOffAmount: "0.00",
        Customer: 24,
        CustomerName: "Chitale Bandu Mithaiwale (Bajirao road)",
        CustomerGSTIN: "27AAAAA0000A1Z5",
        Party: 4,
        PartyName: "Shade No-44",
        PartyGSTIN: "22AAAAA0000A1Z5",
        InvoiceItems: []
    }
    for (let index2 = 0; index2 < isRowLength; index2++) {
        parentData.id = 100 + index;
        parentData.InvoiceItems.push(innerdataFunc(index2))
    }
    return parentData
}
export const dataGenrator = () => {

    const dataArr = []
    for (let index = 0; index < isParentLength; index++) {
        dataArr.push(outerdatfunc(index))

    }
    return dataArr
}






export const Data1 = {
    id: 101,
    InvoiceDate: "2023-06-17",
    InvoiceNumber: 8,
    FullInvoiceNumber: "IN8",
    GrandTotal: "90362.00",
    RoundOffAmount: "0.31",
    Customer: 389,
    CustomerName: "Bedekar Super Market",
    CustomerGSTIN: "",
    Party: 97,
    PartyName: "Demo DD",
    PartyGSTIN: "27AAAAA0000A1Z5",
    PartyFSSAINo: "20400000000471",
    CustomerFSSAINo: "",
    PartyState: "Maharashtra",
    CustomerState: "Maharashtra",
    PartyAddress: "Sadashiv Peth, Pune",
    CustomerAddress: "Rambaug Colony.",
    DriverName: null,
    VehicleNo: null,
    CreatedOn: "2023-06-17T21:26:42.460558",
    InvoiceItems: [
        {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        },
        {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        },
        {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        },
        {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, {
            Item: 4,
            ItemName: "Bakarwadi 3 Pcs",
            Quantity: "1.000",
            MRP: 624,
            MRPValue: "15.00",
            Rate: "11.85",
            TaxType: "GST",
            UnitName: "No",
            BaseUnitQuantity: "1.000",
            GST: 4,
            GSTPercentage: "12.00",
            MarginValue: null,
            BasicAmount: "10.66",
            GSTAmount: "1.28",
            CGST: "0.64",
            SGST: "0.64",
            IGST: "0.00",
            CGSTPercentage: "6.00",
            SGSTPercentage: "6.00",
            IGSTPercentage: "0.00",
            Amount: "11.94",
            BatchCode: "0",
            BatchDate: "2023-06-14",
            HSNCode: "21069099",
            Discount: "10.00",
            DiscountAmount: "1.19"
        }, 
    ],
    InvoicesReferences: [
        {
            Order: 196,
            FullOrderNumber: "PO11"
        }
    ]
}



