export const POST_GO_BUTTON_FOR_DEMAND="POST_GO_BUTTON_FOR_DEMAND"
export const POST_GO_BUTTON_FOR_DEMAND_SUCCESS="POST_GO_BUTTON_FOR_DEMAND_SUCCESS"

export const POST_DEMAND="POST_DEMAND"
export const POST_DEMAND_SUCCESS="POST_DEMAND_SUCCESS"




