export const SAVE_STOCK_ENTRY_ACTION = 'SAVE_STOCK_ENTRY_ACTION'
export const SAVE_STOCK_ENTRY_SUCCESS = 'SAVE_STOCK_ENTRY_SUCCESS'

export const STOCK_ENTRY_API_ERROR_ACTION = 'STOCK_ENTRY_API_ERROR_ACTION'
