export const GET_EMPLOYEE_FOR_USER_REGISTRATION="GET_EMPLOYEE_FOR_USER_REGISTRATION"
export const GET_EMPLOYEE_FOR_USER_REGISTRATION_SUCCESS="GET_EMPLOYEE_FOR_USER_REGISTRATION_SUCCESS"

export const GET_ROLE="GET_ROLE"
export const GET_ROLE_SUCCESS="GET_ROLE_SUCCESS"

export const ADD_USER="ADD_USER"
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"

export const GET_USER="GET_USER"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"

export const DELETE_USER="DELETE_USER"
export const DELETE_SUCCESS="DELETE_SUCCESS"

export const EDIT_USER="EDIT_USER"
export const EDIT_SUCCESS="EDIT_SUCCESS"

export const UPDATE_USER="UPDATE_USER"
export const UPDATE_SUCCESS="UPDATE_SUCCESS"

export const GET_USER_PARTIES_FOR_USER_MASTER="GET_USER_PARTIES_FOR_USER_MASTER"
export const GET_USER_PARTIES_FOR_USER_MASTER_SUCCESS="GET_USER_PARTIES_FOR_USER_MASTER_SUCCESS"

