export const BREADCRUMB_ITEM_NAME = "BREADCRUMB_ITEM_NAME"

export const BREADCRUMB_SHOW_COUNT_LABLE = "BREADCRUMB_SHOW_COUNT_LABLE"
export const COMMON_BREADCRUMB_ALL_DETAIL = "COMMON_BREADCRUMB_ALL_DETAIL"
export const COMMON_BREADCRUMB_ALL_DETAIL_redux = "COMMON_BREADCRUMB_ALL_DETAIL_redux"
