export const BREADCRUMB_ITEM_NAME = "BREADCRUMB_ITEM_NAME"

export const BREADCRUMB_DOWN_BTN_DATA = "BREADCRUMB_DOWN_BTN_DATA"
export const BREADCRUMB_SHOW_COUNT_LABLE = "BREADCRUMB_SHOW_COUNT_LABLE"

export const BREADCRUMB_REST = "BREADCRUMB_REST"

export const COMMON_BREADCRUMB_ALL_DETAIL = "COMMON_BREADCRUMB_ALL_DETAIL"

// export const COMMON_BREADCRUMB_ALL_DETAIL_redux = "COMMON_BREADCRUMB_ALL_DETAIL_redux"
