export const ITEM_SALE_GO_BUTTON_API = 'ITEM_SALE_GO_BUTTON_API'
export const ITEM_SALE_GO_BUTTON_API_SUCCESS = 'ITEM_SALE_GO_BUTTON_API_SUCCESS'

export const ITEM_SALE_REPORT_API_ERROR_ACTION = 'ITEM_SALE_REPORT_API_ERROR_ACTION'