export const InvoiceFakeData = {

  "InvoiceID": 154245,
  "InvoiceDate": "2022-04-13T00:00:00",
  "GSTIN": "27ABDPG6424C1Z4",
  "EWaYBill":"1524247514",
  "BilByName":"M/s.B.G.Chitale",
  "BilByAdr":"Bhilawadi Station Tal:Palus,Dist:Sangli",
  "BilByState":"Maharashtra (27)",
  "BilByGSTIN":"27AABFB3828J1ZH",
  "BilByFSSAI":"10012022000033",
  "BilToName":"Chaitanya Marketing",
  "BilToAdr":"D-4/5,Industrial Estete-Bicholim Goa",
  "BilToState":"GOA (30)",
  "BilToGSTIN":"30AABFB3828J1LK",
  "BilToFSSAI":"40012022000039",

  "GrandTotal": 12680.63,
  "InvoiceServiceItems": [
    {
      "InvoiceID": "5 % First",
      "InvoiceItemID": 2033135,
      "ItemID": 263,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.4,
      "Rate": 235.94,
      "MRP": 0.0,
      "BasicAmount": 3020.03,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 151.0,
      "Amount": 0.0,
      "CGST": 75.5,
      "SGST": 75.5,
      "IGST": 0.0,
      "CGSTPercentage": 2.5,
      "SGSTPercentage": 2.5,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3171.03,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033135,
          "BatchCode": "202204135537-1",
          "BatchDate": " ",
          "Quantity": 12.8
        }
      ]
    },
    
    {
      "InvoiceID": 228684,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 280.65,
      "MRP": 0.0,
      "BasicAmount": 3367.8,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 84.2,
      "SGST": 84.2,
      "IGST": 0.0,
      "CGSTPercentage": 2.5,
      "SGSTPercentage": 2.5,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3536.19,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    {
      "InvoiceID": 228684,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 280.65,
      "MRP": 0.0,
      "BasicAmount": 3367.8,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 84.2,
      "SGST": 84.2,
      "IGST": 0.0,
      "CGSTPercentage": 2.5,
      "SGSTPercentage": 2.5,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3536.19,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    {
      "InvoiceID": 228684,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 280.65,
      "MRP": 0.0,
      "BasicAmount": 3367.8,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 84.2,
      "SGST": 84.2,
      "IGST": 0.0,
      "CGSTPercentage": 2.5,
      "SGSTPercentage": 2.5,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3536.19,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    {
      "InvoiceID": 228684,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 280.65,
      "MRP": 0.0,
      "BasicAmount": 3367.8,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 84.2,
      "SGST": 84.2,
      "IGST": 0.0,
      "CGSTPercentage": 2.5,
      "SGSTPercentage": 2.5,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3536.19,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    
    {
      "InvoiceID": "5% Last",
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 280.65,
      "MRP": 0.0,
      "BasicAmount": 3367.8,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 84.2,
      "SGST": 84.2,
      "IGST": 0.0,
      "CGSTPercentage": 2.5,
      "SGSTPercentage": 2.5,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3536.19,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
     {
            "InvoiceID": "12% First",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          
          {
            "InvoiceID": "12% last",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "18% First",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "04901212 Full Cream Paesteurised Milk Dahi 200 g Pouch",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "04901212 Full Cream Shrikhand Badam Pista 250 gm",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "18% Last",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 280.65,
            "MRP": 0.0,
            "BasicAmount": 3367.8,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 84.2,
            "SGST": 84.2,
            "IGST": 0.0,
            "CGSTPercentage": 2.5,
            "SGSTPercentage": 2.5,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3536.19,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
         
  ]
}

