export const GET_IB_INVOICE_LIST_PAGE = 'GET_IB_INVOICE_LIST_PAGE'
export const GET_IB_INVOICE_LIST_PAGE_SUCCESS = 'GET_IB_INVOICE_LIST_PAGE_SUCCESS'

export const IB_INVOICE_LIST_FILTERS = 'IB_INVOICE_LIST_FILTERS'

export const INWARD_BUTTON_ID = 'INWARD_BUTTON_ID'
export const INWARD_BUTTON_ID_SUCCESS = 'INWARD_BUTTON_ID_SUCCESS'

export const MAKE_IB_INVOICE = 'MAKE_IB_INVOICE'
export const MAKE_IB_INVOICE_SUCCESS = 'MAKE_IB_INVOICE_SUCCESS'