export const GET_SUPPLIER = 'GET_SUPPLIER'
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS'

export const GET_SUPPLIER_ADDRESS = 'GET_SUPPLIER_ADDRESS'
export const GET_SUPPLIER_ADDRESS_SUCCESS = 'GET_SUPPLIER_ADDRESS_SUCCESS'

export const GET_ORDER_TYPE = 'GET_ORDER_TYPE'
export const GET_ORDER_TYPE_SUCCESS = 'GET_ORDER_TYPE_SUCCESS'



