export const GET_SUPPLIER = 'GET_SUPPLIER'
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS'

export const GET_SUPPLIER_ADDRESS = 'GET_SUPPLIER_ADDRESS'
export const GET_SUPPLIER_ADDRESS_SUCCESS = 'GET_SUPPLIER_ADDRESS_SUCCESS'




