
export const POST_IMPORT_FIELD = "POST_IMPORT_FIELD"
export const POST_IMPORT_FIELD_SUCCESS = "POST_IMPORT_FIELD_SUCCESS"

export const GET_IMPORT_FIELD_LIST = "GET_IMPORT_FIELD_LIST"
export const  GET_IMPORT_FIELD_LIST_SUCCESS ="GET_IMPORT_FIELD_LIST_SUCCESS"

export const DELETE_IMPORT_FIELD_ID = "DELETE_IMPORT_FIELD_ID"
export const  DELETE_IMPORT_FIELD_ID_SUCCESS='DELETE_IMPORT_FIELD_ID_SUCCESS'

export const EDIT_IMPORT_FIELD_ID = "EDIT_IMPORT_FIELD_ID"
export const EDIT_IMPORT_FIELD_ID_SUCCESS='EDIT_IMPORT_FIELD_ID_SUCCESS'

export const UPDATE_IMPORT_FIELD_ID = "UPDATE_IMPORT_FIELD_ID"
export const UPDATE_IMPORT_FIELD_ID_SUCCESS = "UPDATE_IMPORT_FIELD_ID_SUCCESS"

export const GET_CONTROLTYPE_DROPDOWN = "GET_CONTROLTYPE_DROPDOWN"
export const GET_CONTROLTYPE_DROPDOWN_SUCCESS = "GET_CONTROLTYPE_DROPDOWN_SUCCESS"

export const GET_VALIDATIONTYPE_DROPDOWN="GET_VALIDATIONTYPE_DROPDOWN"
export const GET_VALIDATIONTYPE_DROPDOWN_SUCCESS="GET_VALIDATIONTYPE_DROPDOWN_SUCCESS"
