// Submit Module  All Action type
export const GET_H_MODULES = "GET_H_MODULES"
export const GET_H_MODULES_SUCCESS = 'GET_H_MODULES_SUCCESS'

export const GET_H_SUB_MODULES = "GET_H_SUB_MODULES_FROM_HPAGE"
export const GET_H_SUB_MODULES_SUCCESS = 'GET_H_SUB_MODULES_SUCCESS'

// Fetch Module_List  All Action type 
export const GET_HPAGES_LIST_DATA = "GET_HPAGES_LIST_DATA"
export const GET_HPAGES_LIST_DATA_SUCCESS = 'GET_HPAGES_LIST_DATA_SUCCESS'

export const SAVE_HPAGES = "SAVE_HPAGES"
export const SAVE_HPAGES_SUCCESS = 'SAVE_HPAGES_SUCCESS'
// export const  FETCH_MODULES_LIST_ERROR='FETCH_MODULES_LIST_ERROR'

export const DELETE_HPAGES_USING_ID = "DELETE_HPAGES_USING_ID"
export const DELETE_H_MODULE_ID_SUCCESS = "DELETE_H_MODULE_ID_SUCCESS"

// // Fetch Module_List  All Action type 
// export const  DELETE_MODULE_ID_SUCCESS='DELETE_MODULE_ID_SUCCESS'
// export const  DELETE_MODULE_ID_ERROR='DELETE_MODULE_ID_ERROR'


export const EDIT_H_PAGES_ID = "EDIT_H_PAGES_ID"
export const EDIT_H_PAGES_ID_SUCCESS = 'EDIT_H_PAGES_ID_SUCCESS'

export const UPDATE_H_PAGES = "UPDATE_H_PAGES"
export const UPDATE_H_PAGES_SUCCESS = 'UPDATE_H_PAGES_SUCCESS'

export const GET_PAGETYPE = "GET_PAGETYPE"
export const GET_PAGETYPE_SUCCESS = 'GET_PAGETYPE_SUCCESS'

export const GET_PAGELIST = "GET_PAGELIST"
export const GET_PAGELIST_SUCCESS = 'GET_PAGELIST_SUCCESS'


export const GET_PAGEACCESS_DROPDOWN_API = 'GET_PAGEACCESS_DROPDOWN_API'
export const GET_PAGEACCESS_DROPDOWN_API_SUCCESS = 'GET_PAGEACCESS_DROPDOWN_API_SUCCESS'

export const GET_CONTROL_TYPES = 'GET_CONTROL_TYPES'
export const GET_CONTROL_TYPES_SUCCESS = 'GET_CONTROL_TYPES_SUCCESS'

export const GET_FIELD_VALIDATIONS = 'GET_FIELD_VALIDATIONS'
export const GET_FIELD_VALIDATIONS_SUCCESS = 'GET_FIELD_VALIDATIONS_SUCCESS'

export const PAGEMASTER_API_ERROR_ACTION = 'PAGEMASTER_API_ERROR_ACTION'




