// post api
export const POST_MRP_MASTER_DATA = "POST_MRP_MASTER_DATA"
export const POST_MRP_MASTER_DATA_SUCCESS = "POST_MRP_MASTER_DATA_SUCCESS"

// Go Button post api
export const POST_GO_BUTTON_DATA = "POST_GO_BUTTON_DATA"
export const POST_GO_BUTTON_DATA_SUCCESS = "POST_GO_BUTTON_DATA_SUCCESS"