// post api
export const POST_MRP_MASTER_DATA = "POST_MRP_MASTER_DATA"
export const POST_MRP_MASTER_DATA_SUCCESS = "POST_MRP_MASTER_DATA_SUCCESS"


// Go Button post api
export const POST_GO_BUTTON_DATA = "POST_GO_BUTTON_DATA"
export const POST_GO_BUTTON_DATA_SUCCESS = "POST_GO_BUTTON_DATA_SUCCESS"

//listpage
export const GET_MRP_LIST_PAGE = "GET_MRP_LIST_PAGE"
export const GET_MRP_LIST_PAGE_SUCCESS = "GET_MRP_LIST_PAGE_SUCCESS"

// delete api
export const DELETE_MRP_LIST_PAGE = "DELETE_MRP_LIST_PAGE"
export const DELETE_MRP_LIST_PAGE_SUCCESS = "DELETE_MRP_LIST_PAGE_SUCCESS"


export const EDIT_MRP_LIST_PAGE ="EDIT_MRP_LIST_PAGE"
export const EDIT_MRP_LIST_PAGE_SUCCESS ="EDIT_MRP_LIST_PAGE_SUCCESS"

export const UPDATE_MRP_LIST_PAGE="UPDATE_MRP_LIST_PAGE"
export const UPDATE_MRP_LIST_PAGE_SUCCESS="UPDATE_MRP_LIST_PAGE_SUCCESS"

