// Submit Module  All Action type
export const GET_FRANCHISE_SALE_DATA = "GET_FRANCHISE_SALE_DATA"
export const  GET_FRANCHISE_SALE_DATA_SUCCESS='GET_FRANCHISE_SALE_DATA_SUCCESS'
export const  GET_POS_SALE_DATA_SUCCESS='GET_POS_SALE_DATA_SUCCESS'
export const  GET_FRANCHISE_SALE_TOP_5_DATA_SUCCESS='GET_FRANCHISE_SALE_TOP_5_DATA_SUCCESS'
