export const fieldData = [
    {
        controlId: 'name',
        ControlType: 2,
        ControlTypeName: "Dropdown",
        fieldLabel: "Name",
        isCompulsory: true,
        defaultSort: true,
        showInListPage: true,
        showInDownload: true,
        downloadDefaultSelect: false,
        regExp: /^.{4,100}$/,
        inValidMsg: "Name is invalid",
    },

    {
        controlId: 'description',
        ControlType: 2,
        ControlTypeName: "text",
        fieldLabel: "Description ",
        isCompulsory: true,
        defaultSort: true,
        showInListPage: true,
        showInDownload: true,
        downloadDefaultSelect: false,
        regExp: /^.{4,100}$/,
        inValidMsg: "Description is invalid",
    },

    {
        controlId: 'dashboard',
        ControlType: 2,
        ControlTypeName: "text",
        fieldLabel: "Dashboard ",
        isCompulsory: true,
        defaultSort: true,
        showInListPage: true,
        showInDownload: true,
        downloadDefaultSelect: false,
        regExp: /^.{4,100}$/,
        inValidMsg: "Dashboard is invalid",
    },

    {
        controlId: 'employeeType',
        controlType: 2,
        controltypeName: "select",
        fieldLabel: "Employee Type ",
        isCompulsory: true,
        defaultSort: true,
        fieldValidation:4,
        fieldValidationName:"10 digit Number",
        showInListPage: true,
        showInDownload: true,
        downloadDefaultSelect: false,
        regExp: "",
        inValidMsg: "Please Select Value",
    },

]