// Submit Module  All Action type
export const GET_POS_STOCK_REPORT_DATA_ACTION = "GET_POS_STOCK_REPORT_DATA_ACTION"
export const  GET_POS_STOCK_REPORT_DATA_ACTION_SUCCESS='GET_POS_STOCK_REPORT_DATA_ACTION_SUCCESS'
export const  GET_POS_SALE_DATA_SUCCESS='GET_POS_SALE_DATA_SUCCESS'
