export const SAVE_BANK_ASSIGN = "SAVE_BANK_ASSIGN"
export const SAVE_BANK_ASSIGN_SUCCESS = "SAVE_BANK_ASSIGN_SUCCESS"

export const PARTY_BANK_FILTER = "PARTY_BANK_FILTER"
export const PARTY_BANK_FILTER_SUCCESS = "PARTY_BANK_FILTER_SUCCESS"