export const GET_DEFAULT_MODULE='GET_DEFAULT_MODULE'
export const GET_DEFAULT_MODULE_SUCCESS='GET_DEFAULT_MODULE_SUCCES'

export const POST_DEFAULT_MODULE_ID='POST_DEFAULT_MODULE_ID'
export const POST_DEFAULT_MODULE_ID_SUCCESS = "POST_DEFAULT_MODULE_ID_SUCCESS"
export const POST_SUB_MODULE = "POST_SUB_MODULE"

export const POST_SUB_MODULE_SUCCESS = "POST_SUB_MODULE_SUCCESS"

export const GET_PAGE_ACCESS = "GET_PAGE_ACCESS"
export const GET_PAGE_ACCESS_SUCCESS = "GET_PAGE_ACCESS_SUCCESS"

export const ADD_PAGE = "ADD_PAGE"
export const ADD_PAGE_SUCCESS = "ADD_PAGE_SUCCESS"