
import {POST_METHOD_HANDLER_FOR_PRODUCT_CATEGORY_TYPE_MASTER_API, POST_METHOD_HANDLER_FOR_PRODUCT_CATEGORY_TYPE_MASTER_API_SUCCESS,GET_METHOD_HANDLER_FOR_PRODUCT_CATEGORY_TYPE_MASTER_API,GET_METHOD_HANDLER_FOR_PRODUCT_CATEGORY_TYPE_MASTER_API_SUCCESS,} from "./actionTypes";

export const PostMethodForProductCategoryTypeMaster = (data) => ({
    type: POST_METHOD_HANDLER_FOR_PRODUCT_CATEGORY_TYPE_MASTER_API,
    data,
  });
  
  export const PostMethod_ForProductCategoryTypeMasterAPISuccess = (data) => ({
    type: POST_METHOD_HANDLER_FOR_PRODUCT_CATEGORY_TYPE_MASTER_API_SUCCESS,
    payload: data,
  });


