export const INVOICE_NUMBER = 'INVOICE_NUMBER'
export const INVOICE_NUMBER_SUCCESS = 'INVOICE_NUMBER_SUCCESS'

<<<<<<< HEAD
export const ADD_BUTTON_FOR_SALES_RETURN = 'ADD_BUTTON_FOR_SALES_RETURN'
export const ADD_BUTTON_FOR_SALES_RETURN_SUCCESS = 'ADD_BUTTON_FOR_SALES_RETURN_SUCCESS'
=======
export const SAVE_SALES_RETURN_MASTER = 'SAVE_SALES_RETURN_MASTER'
export const SAVE_SALES_RETURN_MASTER_SUCCESS = 'SAVE_SALES_RETURN_MASTER_SUCCESS'

export const SALES_RETURN_LIST_API = 'SALES_RETURN_LIST_API'
export const SALES_RETURN_LIST_API_SUCCESS = 'SALES_RETURN_LIST_API_SUCCESS'

export const DELETE_SALES_RETURN_ID = 'DELETE_SALES_RETURN_ID'
export const DELETE_SALES_RETURN_ID_SUCCESS = 'DELETE_SALES_RETURN_ID_SUCCESS'
>>>>>>> NewCommon
