export const INVOICE_NUMBER = 'INVOICE_NUMBER'
export const INVOICE_NUMBER_SUCCESS = 'INVOICE_NUMBER_SUCCESS'

export const SAVE_SALES_RETURN_MASTER = 'SAVE_SALES_RETURN_MASTER'
export const SAVE_SALES_RETURN_MASTER_SUCCESS = 'SAVE_SALES_RETURN_MASTER_SUCCESS'