export const INVOICE_NUMBER = 'INVOICE_NUMBER'
export const INVOICE_NUMBER_SUCCESS = 'INVOICE_NUMBER_SUCCESS'

export const ADD_BUTTON_FOR_SALES_RETURN = 'ADD_BUTTON_FOR_SALES_RETURN'
export const ADD_BUTTON_FOR_SALES_RETURN_SUCCESS = 'ADD_BUTTON_FOR_SALES_RETURN_SUCCESS'