export const GET_GRN_ITEM_MODE_2 = 'GET_GRN_ITEM_MODE_2'
export const GET_GRN_ITEM_MODE_2_SUCCESS = 'GET_GRN_ITEM_MODE_2_SUCCESS'

export const GET_CHALLAN_LIST_PAGE = 'GET_CHALLAN_LIST_PAGE'
export const GET_CHALLAN_LIST_PAGE_SUCCESS = 'GET_CHALLAN_LIST_PAGE_SUCCESS'

export const POST_GRN_FROM_GRN_PAGE = 'POST_GRN_FROM_GRN_PAGE'
export const POST_GRN_FROM_GRN_PAGE_SUCCESS = 'POST_GRN_FROM_GRN_PAGE_SUCCESS'

export const EDIT_GRN_FOR_GRN_PAGE = 'EDIT_GRN_FOR_GRN_PAGE'
export const EDIT_GRN_FOR_GRN_PAGE_SUCCESS = 'EDIT_GRN_FOR_GRN_PAGE_SUCCESS'

export const UPDATE_GRN_ID_FROM_GRN_PAGE = 'UPDATE_GRN_ID_FROM_GRN_PAGE'
export const UPDATE_GRN_ID_FROM_GRN_PAGE_SUCCESS = 'UPDATE_GRN_ID_FROM_GRN_PAGE_SUCCESS'
// 
export const DELETE_CHALLAN_FOR_CHALLAN_PAGE = 'DELETE_CHALLAN_FOR_GRN_PAGE'
export const DELETE_CHALLAN_FOR_CHALLAN_PAGE_SUCCESS = 'DELETE_CHALLAN_FOR_GRN_PAGE_SUCCESS'

export const GO_BUTTON_FOR_GRN_PAGE = 'GO_BUTTON_FOR_GRN_PAGE'
export const GO_BUTTON_FOR_GRN_PAGE_SUCCESS = 'GO_BUTTON_FOR_GRN_PAGE_SUCCESS'

export const MAKE_CHALLAN_GET_API = 'MAKE_CHALLAN_GET_API'
export const MAKE_CHALLAN_GET_API_SUCCESS = 'MAKE_CHALLAN_GET_API_SUCCESS'



export const SET_CHALLAN_LIST_FILTERS = 'SET_GRN_LIST_FILTERS'





