export const GET_GRN_ITEM_MODE_2 = 'GET_GRN_ITEM_MODE_2'
export const GET_GRN_ITEM_MODE_2_SUCCESS = 'GET_GRN_ITEM_MODE_2_SUCCESS'

export const GET_CHALLAN_LIST_PAGE = 'GET_CHALLAN_LIST_PAGE'
export const GET_CHALLAN_LIST_PAGE_SUCCESS = 'GET_CHALLAN_LIST_PAGE_SUCCESS'

export const ITEM_CHALLAN_POST_API = 'ITEM_CHALLAN_POST_API'
export const POST_ITEM_CHALLAN_PAGE_SUCCESS = 'POST_ITEM_CHALLAN_PAGE_SUCCESS'

export const CHALLAN_POST_API = 'CHALLAN_POST_API'
export const CHALLAN_POST_API_SUCCESS = 'CHALLAN_POST_API_SUCCESS'





export const DELETE_CHALLAN_FOR_CHALLAN_PAGE = 'DELETE_CHALLAN_FOR_GRN_PAGE'
export const DELETE_CHALLAN_FOR_CHALLAN_PAGE_SUCCESS = 'DELETE_CHALLAN_FOR_GRN_PAGE_SUCCESS'

export const GO_BUTTON_CHALLAN_POST_API = 'GO_BUTTON_CHALLAN_POST_API'
export const GO_BUTTON_CHALLAN_POST_API_SUCCESS = 'GO_BUTTON_CHALLAN_POST_API_SUCCESS'

export const MAKE_CHALLAN_GET_API = 'MAKE_CHALLAN_GET_API'
export const MAKE_CHALLAN_GET_API_SUCCESS = 'MAKE_CHALLAN_GET_API_SUCCESS'

export const GO_BUTTON_FOR_CHALLAN_ADD = 'GO_BUTTON_FOR_CHALLAN_ADD'
export const GO_BUTTON_FOR_CHALLAN_ADD_SUCCESS = 'GO_BUTTON_FOR_CHALLAN_ADD_SUCCESS'

export const SET_CHALLAN_LIST_FILTERS = 'SET_GRN_LIST_FILTERS'





