
export const RECEIPT_GO_BUTTON_MASTER="RECEIPT_GO_BUTTON_MASTER"
export const RECEIPT_GO_BUTTON_MASTER_SUCCESS="RECEIPT_GO_BUTTON_MASTER_SUCCESS"

export const DEPOSITOR_BANK_FILTER="DEPOSITOR_BANK_FILTER"
export const DEPOSITOR_BANK_FILTER_SUCCESS="DEPOSITOR_BANK_FILTER_SUCCESS"


export const POST_RECEIPT_LIST_PAGE = 'POST_RECEIPT_LIST_PAGE'
export const POST_RECEIPT_LIST_PAGE_SUCCESS = 'POST_RECEIPT_LIST_PAGE_SUCCESS'

export const RECEIPT_LIST_FILTERS = 'RECEIPT_LIST_FILTERS'

export const SAVE_RECEIPT_MASTER="SAVE_RECEIPT_MASTER"
export const SAVE_RECEIPT_MASTER_SUCCESS="SAVE_RECEIPT_MASTER_SUCCESS"

