
export const RECEIPT_GO_BUTTON_MASTER="RECEIPT_GO_BUTTON_MASTER"
export const RECEIPT_GO_BUTTON_MASTER_SUCCESS="RECEIPT_GO_BUTTON_MASTER_SUCCESS"

export const DEPOSITOR_BANK_FILTER="DEPOSITOR_BANK_FILTER"
export const DEPOSITOR_BANK_FILTER_SUCCESS="DEPOSITOR_BANK_FILTER_SUCCESS"

export const SAVE_RECEIPT_MASTER="SAVE_RECEIPT_MASTER"
export const SAVE_RECEIPT_MASTER_SUCCESS="SAVE_RECEIPT_MASTER_SUCCESS"

export const RECEIPT_LIST_API = 'RECEIPT_LIST_API'
export const RECEIPT_LIST_API_SUCCESS = 'RECEIPT_LIST_API_SUCCESS'

export const RECEIPT_TYPE_API = 'RECEIPT_TYPE_API'
export const RECEIPT_TYPE_API_SUCCESS = 'RECEIPT_TYPE_API_SUCCESS'