export const GO_BUTTON_POST_FOR_INVOICE = 'GO_BUTTON_POST_FOR_INVOICE'
export const GO_BUTTON_POST_FOR_INVOICE_SUCCESS = 'GO_BUTTON_POST_FOR_INVOICE_SUCCESS'

export const POST_INVOICE_MASTER = 'POST_INVOICE_MASTER'
export const POST_INVOICE_MASTER_SUCCESS = 'POST_INVOICE_MASTER_SUCCESS'

export const GET_INVOICE_LIST_PAGE = 'GET_INVOICE_LIST_PAGE'
export const GET_INVOICE_LIST_PAGE_SUCCESS = 'GET_INVOICE_LIST_PAGE_SUCCESS'