// export const POST_MODULE="POST_MODULE"
// export const GET_H_MODULE_SUCCESS="GET_H_MODULE_SUCCESS"

export const POST_SUB_MODULE_ID="POST_SUB_MODULE_ID"
export const POST_SUB_MODULE_SUCCESS_ID="POST_SUB_MODULE_SUCCESS_ID"

export const GET_SUB_MODULES="GET_SUB_MODULES"
export const GET_SUB_MODULES_SUCCESS="GET_SUB_MODULES_SUCCESS"

export const DELETE_SUB_MODULES_USING_ID="DELETE_SUB_MODULES_USING_ID"
export const DELETE_SUB_MODULES_USING_ID_SUCCESS="DELETE_SUB_MODULES_USING_ID_SUCCESS"

export const GET_SUB_MODULES_EDIT_DATA_USING_ID="GET_SUB_MODULES_EDIT_DATA_USING_ID,"
export const GET_SUB_MODULES_EDIT_DATA_USING_ID_SUCCESS="GET_SUB_MODULES_EDIT_DATA_USING_ID_SUCCESS"

export const UPDATE_MODULE="UPDATE_MODULE"
export const UPDATE_MODULE_SUCCESS="UPDATE_MODULE_SUCCESS "
 