export const SAVE_CLAIM_TRACKING_ENTRY = "SAVE_CLAIM_TRACKING_ENTRY"
export const SAVE_CLAIM_TRACKING_ENTRY_SUCCESS = "SAVE_CLAIM_TRACKING_ENTRY_SUCCESS"

export const CLAIM_TRACKING_ENTRY_API_ERROR_ACTION = "CLAIM_TRACKING_ENTRY_API_ERROR_ACTION"

