export const SAVE_CLAIM_TRACKING_ENTRY = "SAVE_CLAIM_TRACKING_ENTRY"
export const SAVE_CLAIM_TRACKING_ENTRY_SUCCESS = "SAVE_CLAIM_TRACKING_ENTRY_SUCCESS"

export const GET_CLAIM_TRACKING_ENTRY_LIST = "GET_CLAIM_TRACKING_ENTRY_LIST"
export const GET_CLAIM_TRACKING_ENTRY_LIST_SUCCESS = "GET_CLAIM_TRACKING_ENTRY_LIST_SUCCESS"

export const CLAIM_TRACKING_ENTRY_API_ERROR_ACTION = "CLAIM_TRACKING_ENTRY_API_ERROR_ACTION"

