export const POST_INWARD = 'POST_INWARD'
export const POST_INWARD_SUCCESS = 'POST_INWARD_SUCCESS'

export const GET_INWARD_LIST_PAGE = 'GET_INWARD_LIST_PAGE'
export const GET_INWARD_LIST_PAGE_SUCCESS = 'GET_INWARD_LIST_PAGE_SUCCESS'

export const INWARD_LIST_FILTERS = 'ORDER_LIST_FILTERS'
