export const COMMON_PARTY_DROPDOWN = "COMMON_PARTY_DROPDOWN"
export const COMMON_PARTY_DROPDOWN_SUCCESS = 'COMMON_PARTY_DROPDOWN_SUCCESS'


export const COMMON_PARTY_DROP_SELECT_ACTION = "COMMON_PARTY_DROP_SELECT_ACTION"
export const COMMON_PARTY_DROP_SELECT_ACTION_SUCCESS = 'COMMON_PARTY_DROP_SELECT_ACTION_SUCCESS'