export const POST_METHOD_FOR_GENERAL_API="POST_METHOD_FOR_GENERAL_API"
export const POST_METHOD_FOR_GENERAL_API_SUCCESS="POST_METHOD_FOR_GENERAL_API_SUCCESS"

export const GET_GENERAL_LIST="GET_GENERAL_LIST"
export const GET_GENERAL_LIST_SUCCESS="GET_GENERAL_LIST_SUCCESS"

export const DELETE_GENERAL_ID="DELETE_GENERAL_ID"
export const DELETE_GENERAL_ID_SUCCESS="DELETE_GENERAL_ID_SUCCESS"

export const EDIT_GENERAL_ID="EDIT_GENERAL_ID"
export const EDIT_GENERAL_ID_SUCCESS="EDIT_GENERAL_ID_SUCCESS"

export const UPDATE_GENERAL_ID="UPDATE_GENERAL_ID"
export const UPDATE_GENERAL_ID_SUCCESS="UPDATE_GENERAL_ID_SUCCESS"

export const GET_TYPE="GET_TYPE"
export const GET_TYPE_SUCCESS="GET_TYPE_SUCCESS"

