
export const GO_BUTTON_IMPORT_MASTER_MAP = "GO_BUTTON_IMPORT_MASTER_MAP"
export const GO_BUTTON_IMPORT_MASTER_MAP_SUCCESS= "GO_BUTTON_IMPORT_MASTER_MAP_SUCCESS"

export const SAVE_IMPORT_MASTER_MAP = "SAVE_IMPORT_MASTER_MAP"
export const SAVE_IMPORT_MASTER_MAP_SUCCESS= "SAVE_IMPORT_MASTER_MAP_SUCCESS"

export const GET_IMPORT_MASTER_MAP_LIST="GET_IMPORT_MASTER_MAP_LIST"
export const GET_IMPORT_MASTER_MAP_LIST_SUCCESS="GET_IMPORT_MASTER_MAP_LIST_SUCCESS"

export const EXCEL_UPLOAD_SAVE="EXCEL_UPLOAD_SAVE"
export const EXCEL_UPLOAD_SAVE_SUCCESS="EXCEL_UPLOAD_SAVE_SUCCESS"



