// post api
export const POST_MARGIN_MASTER_DATA = "POST_MARGIN_MASTER_DATA"
export const POST_MARGIN_MASTER_DATA_SUCCESS = "POST_MARGIN_MASTER_DATA_SUCCESS"

//listpage
export const GET_MARGIN_LIST_PAGE = "GET_MARGIN_LIST_PAGE"
export const GET_MARGIN_LIST_PAGE_SUCCESS = "GET_MARGIN_LIST_PAGE_SUCCESS"

// delete api
export const DELETE_MARGIN_LIST_PAGE = "DELETE_MARGIN_LIST_PAGE"
export const DELETE_MARGIN_LIST_PAGE_SUCCESS = "DELETE_MARGIN_LIST_PAGE_SUCCESS"


export const EDIT_MARGIN_LIST_PAGE ="EDIT_MARGIN_LIST_PAGE"
export const EDIT_MARGIN_LIST_PAGE_SUCCESS ="EDIT_MARGIN_LIST_PAGE_SUCCESS"

export const UPDATE_MARGIN_LIST_PAGE="UPDATE_MARGIN_LIST_PAGE"
export const UPDATE_MARGIN_LIST_PAGE_SUCCESS="UPDATE_MARGIN_LIST_PAGE_SUCCESS"

// Go Button post api
export const POST_GO_BUTTON_FOR_MARGIN_MASTER = "POST_GO_BUTTON_FOR_MARGIN_MASTER"
export const POST_GO_BUTTON_FOR_MARGIN_MASTER_SUCCESS = "POST_GO_BUTTON_FOR_MARGIN_MASTER_SUCCESS"