export const rollData =  [
    {
      ID: 0,
      RoleID: 3,
      DivisionID: 3,
      ModuleID: 2,
      CompanyID: 1,
      ModuleName: "Administration",
      DisplayIndex: 0,
      RoleAccessList: [
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 26,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 21,
          RelatedPagePath: null,
          ActualPagePath: "modulesMaster",
          PageName: "Module Master",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 110,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 0,
          RelatedPagePath: null,
          ActualPagePath: "modulesList",
          PageName: "Modules List",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 111,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 0,
          RelatedPagePath: null,
          ActualPagePath: "companymaster",
          PageName: "Company Master",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 112,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 0,
          RelatedPagePath: null,
          ActualPagePath: "companyList",
          PageName: "CompanyList",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 115,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 114,
          RelatedPagePath: null,
          ActualPagePath: "pagesmaster",
          PageName: "HPage",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 115,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 114,
          RelatedPagePath: null,
          ActualPagePath: "pagesList",
          PageName: "HPage List",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 207,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 0,
          RelatedPagePath: null,
          ActualPagePath: "RoleMaster",
          PageName: "RoleMaster",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 135,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 0,
          RelatedPagePath: null,
          ActualPagePath: "roleList",
          PageName: "RoleList",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        
      ]
    },
    {
      ID: 0,
      RoleID: 3,
      DivisionID: 3,
      ModuleID: 15,
      CompanyID: 1,
      ModuleName: "Master",
      DisplayIndex: 0,
      RoleAccessList: [
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 8,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 7,
          RelatedPagePath: null,
          ActualPagePath: "AddEmployee",
          PageName: "Employee Master",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
        {
          ID: 0,
          RoleID: 0,
          DivisionID: 0,
          ModuleID: 0,
          ModuleName: null,
          SubModuleID: 0,
          SubModuleName: null,
          PageID: 10,
          IsShow: false,
          IsShowAddPage: false,
          IsAdd: false,
          IsEditSelf: false,
          IsEdit: false,
          IsView: false,
          IsDeleteSelf: false,
          IsDelete: false,
          IsPrint: false,
          CompanyID: 0,
          RelatedPageID: 9,
          RelatedPagePath: null,
          ActualPagePath: "Employee_List",
          PageName: "Employee List",
          SubModuleDisplayIndex: 0,
          ModuleDisplayIndex: 0,
          PageAttributes: null,
          Name: null
        },
      
      ]
    },
    
  ]
