export const GET_ORDER_ITEMS_FOR_ORDER_PAGE = "GET_ORDER_ITEMS_FOR_ORDER_PAGE"
export const GET_ORDER_ITEMS_FOR_ORDER_PAGE_SUCCESS='GET_ORDER_ITEMS_FOR_ORDER_PAGE_SUCCESS'

export const  SUBMIT_ORDER_FROM_ORDER_PAGE='SUBMIT_ORDER_FROM_ORDER_PAGE'
export const  SUBMIT_ORDER_FROM_ORDER_PAGE_SUCCESS='SUBMIT_ORDER_FROM_ORDER_PAGE_SUCCESS'

export const  GET_ORDER_LIST='GET_ORDER_LIST'
export const  GET_ORDER_LIST_SUCCESS='GET_ORDER_LIST_SUCCESS'

export const  GET_ORDER_LIST_MESSAGE='GET_ORDER_LIST_MESSAGE'

export const  EDIT_ORDER='EDIT_ORDER'
export const  EDIT_ORDER_SUCCESS='EDIT_ORDER_SUCCESS'

export const GET_DIVISIONORDER_LIST='GET_DIVISIONORDER_LIST'
export const  GET_DIVISIONORDER_LIST_SUCCESS='GET_DIVISIONORDER_LIST_SUCCESS'
 
