export const POST_METHOD_CREDIT_API="POST_METHOD_CREDIT_API"
export const POST_METHOD_CREDIT_API_SUCCESS="POST_METHOD_CREDIT_API_SUCCESS"

export const GET_CREDIT_LIST="GET_CREDIT_LIST"
export const GET_CREDIT_LIST_SUCCESS="GET_CREDIT_LIST_SUCCESS"


export const DELETE_CREDIT_LIST_ID="DELETE_CREDIT_LIST_ID"
export const DELETE_CREDIT_LIST_ID_SUCCESS="DELETE_CREDIT_LIST_ID_SUCCESS"

export const CREDITDEBIT_TYPE="CREDITDEBIT_TYPE"
export const CREDITDEBIT_TYPE_SUCCESS="CREDITDEBIT_TYPE_SUCCESS"

// export const UPDATE_CREDIT_ID="UPDATE_CREDIT_ID"
// export const UPDATE_CREDIT_ID_SUCCESS="UPDATE_CREDIT_ID_SUCCESS"

export const SAVE_CREDIT = "SAVE_CREDIT"
export const SAVE_CREDIT_SUCCESS= "SAVE_CREDIT_SUCCESS"