// post api
export const POST_PRICE_LIST_DATA = "POST_PRICE_LIST_DATA"
export const POST_PRICE_LIST_DATA_SUCCESS = "POST_PRICE_LIST_DATA_SUCCESS"

// GET api
export const GET_PRICE_LIST_DATA = "GET_PRICE_LIST_DATA"
export const GET_PRICE_LIST_DATA_SUCCESS = "GET_PRICE_LIST_DATA_SUCCESS"

// delete api
export const DELETE_PRICE_LIST = "DELETE_PRICE_LIST"
export const DELETE_PRICE_LIST_SUCCESS = "DELETE_PRICE_LIST_SUCCESS"


export const EDIT_PRICE_LIST ="EDIT_PRICE_LIST"
export const EDIT_PRICE_LIST_SUCCESS="EDIT_PRICE_LIST_SUCCESS"

export const UPDATE_PRICE_LIST="UPDATE_PRICE_LIST"
export const UPDATE_PRICE_LIST_SUCCESS="UPDATE_PRICE_LIST_SUCCESS"