
export const GO_BUTTON_API_SAP_LEDGER = "GO_BUTTON_API_SAP_LEDGER"
export const GO_BUTTON_API_SAP_LEDGER_SUCCESS= "GO_BUTTON_API_SAP_LEDGER_SUCCESS"

export const GET_EXCELBUTTON_API = "GET_EXCELBUTTON_API"
export const GET_EXCELBUTTON_API_SUCCESS= "GET_EXCELBUTTON_API_SUCCESS"