export const SAVE_MANAGEMENT_PARTIES = "SAVE_MANAGEMENT_PARTIES"
export const SAVE_MANAGEMENT_PARTIES_SUCCESS = 'SAVE_MANAGEMENT_PARTIES_SUCCESS'

export const GET_PARTY_TABLE_LIST = "GET_PARTY_TABLE_LIST"
export const GET_PARTY_TABLE_LIST_SUCCESS = 'GET_PARTY_TABLE_LIST_SUCCESS'