export const GET_GRN_ITEMS_FOR_GRN_PAGE = "GET_GRN_ITEMS_FOR_GRN_PAGE"
export const GET_GRN_ITEMS_FOR_GRN_PAGE_SUCCESS='GET_GRN_ITEMS_FOR_GRN_PAGE_SUCCESS'

export const  POST_GRN_FROM_GRN_PAGE='POST_GRN_FROM_GRN_PAGE'
export const  POST_GRN_FROM_GRN_PAGE_SUCCESS='POST_GRN_FROM_GRN_PAGE_SUCCESS'

export const  GET_GRN_LIST='GET_GRN_LIST'
export const  GET_GRN_LIST_SUCCESS='GET_GRN_LIST_SUCCESS'

export const  EDIT_GRN_FOR_GRN_PAGE='EDIT_GRN_FOR_GRN_PAGE'
export const  EDIT_GRN_FOR_GRN_PAGE_SUCCESS='EDIT_GRN_FOR_GRN_PAGE_SUCCESS'

export const GET_DIVISIONGRN_LIST='GET_DIVISIONGRN_LIST'
export const  GET_DIVISIONGRN_LIST_SUCCESS='GET_DIVISIONGRN_LIST_SUCCESS'

export const UPDATE_GRN_ID_FROM_GRN_PAGE='UPDATE_GRN_ID_FROM_GRN_PAGE'
export const  UPDATE_GRN_ID_FROM_GRN_PAGE_SUCCESS='UPDATE_GRN_ID_FROM_GRN_PAGE_SUCCESS'

export const DELETE_GRN_FOR_GRN_PAGE='DELETE_GRN_FOR_GRN_PAGE'
export const DELETE_GRN_FOR_GRN_PAGE_SUCCESS='DELETE_GRN_FOR_GRN_PAGE_SUCCESS'

export const GO_BUTTON_FOR_GRN_PAGE='GO_BUTTON_FOR_GRN_PAGE'
export const GO_BUTTON_FOR_GRN_PAGE_SUCCESS='GO_BUTTON_FOR_GRN_PAGE_SUCCESS'

export const GET_GRN_LIST_PAGE='GET_GRN_LIST_PAGE'
export const GET_GRN_LIST_PAGE_SUCCESS='GET_GRN_LIST_PAGE_SUCCESS'


