export const POST_DIVISION_TYPE_API = "POST_DIVISION_TYPE_API"
export const  POST_DIVISION_TYPE_API_SUCCESS='POST_DIVISION_TYPE_API_SUCCESS'

export const GET_DIVISION_TYPE_LIST = "GET_DIVISION_TYPE_LIST"
export const  GET_DIVISION_TYPE_LIST_SUCCESS='GET_DIVISION_TYPE_LIST_SUCCESS'

export const DELETE_DIVISION_TYPE_ID = "DELETE_DIVISION_TYPE_ID"
export const  DELETE_DIVISION_TYPE_ID_SUCCESS='DELETE_DIVISION_TYPE_ID_SUCCESS'

export const EDIT_DIVISION_TYPE_ID = "EDIT_DIVISION_TYPE_ID"
export const  EDIT_DIVISION_TYPE_ID_SUCCESS='EDIT_DIVISION_TYPE_ID_SUCCESS'

export const UPDATE_DIVISION_TYPE_ID = "UPDATE_DIVISION_TYPE_ID"
export const  UPDATE_DIVISION_TYPE_ID_SUCCESS='UPDATE_DIVISION_TYPE_ID_SUCCESS'