export const  Data= {
    id: 21,
    ItemName:"Sugar",
    InvoiceDate: "2023-01-21",
    Todate: "2023-01-21",
    InvoiceNumber: 2,
    FullInvoiceNumber: "IN 2",
    GrandTotal: "61097.00",
    RoundOffBalance: "0.88",
    Customer: 24,
    CompanyName: "CHITLE SWEETS AND SNACKS PVT.LTD",
    CustomerName: "Chitale Bandu Mithaiwale (Bajirao road)",
    CustomerGSTIN: "27AAAAA0000A1Z5",
    Party: 4,
    Time:"1:12:45 PM",
    PartyName: "Shade No-44",
    PartyGSTIN: "22AAAAA0000A1Z5",
    Open:"324545",
    Close:"656576",
    InvoiceItems: [
      {
        
        Item: 44,
        Particulars: "Shed No 44",
        Quantity: "cash transactions",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "cash transactions",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "200.00",
        GSTBalance: "10.00",
        InwardQuantity: "5.00",
        SGST: "5.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "210.00",
        OutQuantity: "0",
        BatchDate: "2023-01-21"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "20.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "20.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "100.00",
        InwardQuantity: "50.00",
        SGST: "50.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2100.00",
        OutQuantity: "45",
        BatchDate: "2023-01-18"
      },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "4454",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "04525",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "5456",
      //   BatchDate: "2023-01-18"
      // },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "30.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "150.00",
        InwardQuantity: "75.00",
        SGST: "75.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "3150.00",
        OutQuantity: "65",
        BatchDate: "2023-01-18"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "10.500",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "10.500",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "28.88",
        InwardQuantity: "14.44",
        SGST: "14.44",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "606.38",
        OutQuantity: "12",
        BatchDate: "2023-01-10"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "6.000",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "11.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "16.50",
        InwardQuantity: "8.25",
        SGST: "8.25",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "346.50",
        OutQuantity: "0",
        BatchDate: "2023-01-18"
      },
      // {
      //   Item: 61,
      //   Particulars: "Shed No 50",
      //   Quantity: "32.000",
      //   MRP: null,
      //   Rate: "65.00",
      //   TaxType: "GST",
      //   UnitName: "Kg",
      //   BaseUnitQuantity: "78.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "104.00",
      //   InwardQuantity: "52.00",
      //   SGST: "52.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2184.00",
      //   OutQuantity: "550",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 44,
      //   Particulars: "Shed No 44",
      //   Quantity: "cash transactions",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "cash transactions",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "200.00",
      //   GSTBalance: "10.00",
      //   InwardQuantity: "5.00",
      //   SGST: "5.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "210.00",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-21"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "20.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "20.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "100.00",
      //   InwardQuantity: "50.00",
      //   SGST: "50.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2100.00",
      //   OutQuantity: "45",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "4454",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "04525",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "5456",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "566",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "566",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "30.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "150.00",
      //   InwardQuantity: "75.00",
      //   SGST: "75.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "3150.00",
      //   OutQuantity: "65",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 60,
      //   Particulars: "Shed No 50",
      //   Quantity: "10.500",
      //   MRP: null,
      //   Rate: "55.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "10.500",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "28.88",
      //   InwardQuantity: "14.44",
      //   SGST: "14.44",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "606.38",
      //   OutQuantity: "12",
      //   BatchDate: "2023-01-10"
      // },
      // {
      //   Item: 60,
      //   Particulars: "Shed No 50",
      //   Quantity: "6.000",
      //   MRP: null,
      //   Rate: "55.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "11.000",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "16.50",
      //   InwardQuantity: "8.25",
      //   SGST: "8.25",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "346.50",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 61,
      //   Particulars: "Shed No 50",
      //   Quantity: "32.000",
      //   MRP: null,
      //   Rate: "65.00",
      //   TaxType: "GST",
      //   UnitName: "Kg",
      //   BaseUnitQuantity: "78.000",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "104.00",
      //   InwardQuantity: "52.00",
      //   SGST: "52.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2184.00",
      //   OutQuantity: "550",
      //   BatchDate: "2023-01-18"
      // },{
      //   Item: 44,
      //   Particulars: "Shed No 44",
      //   Quantity: "cash transactions",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "cash transactions",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "200.00",
      //   GSTBalance: "10.00",
      //   InwardQuantity: "12.00",
      //   SGST: "12.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "210.00",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-21"
      // },
      
     
      
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "12.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "5456",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "566",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "566",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "30.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "150.00",
      //   InwardQuantity: "75.00",
      //   SGST: "75.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "3150.00",
      //   OutQuantity: "65",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 60,
      //   Particulars: "Shed No 50",
      //   Quantity: "10.500",
      //   MRP: null,
      //   Rate: "55.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "10.500",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "28.88",
      //   InwardQuantity: "14.44",
      //   SGST: "14.44",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "606.38",
      //   OutQuantity: "12",
      //   BatchDate: "2023-01-10"
      // },
      // {
      //   Item: 60,
      //   Particulars: "Shed No 50",
      //   Quantity: "6.000",
      //   MRP: null,
      //   Rate: "55.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "11.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "16.50",
      //   InwardQuantity: "8.25",
      //   SGST: "8.25",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "346.50",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 61,
      //   Particulars: "Shed No 50",
      //   Quantity: "32.000",
      //   MRP: null,
      //   Rate: "65.00",
      //   TaxType: "GST",
      //   UnitName: "Kg",
      //   BaseUnitQuantity: "78.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "104.00",
      //   InwardQuantity: "52.00",
      //   SGST: "52.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2184.00",
      //   OutQuantity: "550",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 44,
      //   Particulars: "Shed No 44",
      //   Quantity: "cash transactions",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "cash transactions",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "200.00",
      //   GSTBalance: "10.00",
      //   InwardQuantity: "1.00",
      //   SGST: "1.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "210.00",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-21"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "20.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "20.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "100.00",
      //   InwardQuantity: "50.00",
      //   SGST: "50.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2100.00",
      //   OutQuantity: "45",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "1.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "4454",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "04525",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "5456",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "566",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "100.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "credit transactions",
      //   GSTBalance: "500.00",
      //   InwardQuantity: "250.00",
      //   SGST: "250.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "10500.00",
      //   OutQuantity: "566",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 46,
      //   Particulars: "Shed No 50",
      //   Quantity: "30.000",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "100.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "150.00",
      //   InwardQuantity: "75.00",
      //   SGST: "75.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "3150.00",
      //   OutQuantity: "65",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 60,
      //   Particulars: "Shed No 50",
      //   Quantity: "10.500",
      //   MRP: null,
      //   Rate: "55.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "10.500",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "28.88",
      //   InwardQuantity: "14.44",
      //   SGST: "14.44",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "606.38",
      //   OutQuantity: "12",
      //   BatchDate: "2023-01-10"
      // },
      // {
      //   Item: 60,
      //   Particulars: "Shed No 50",
      //   Quantity: "6.000",
      //   MRP: null,
      //   Rate: "55.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "11.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "16.50",
      //   InwardQuantity: "8.25",
      //   SGST: "8.25",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "346.50",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 61,
      //   Particulars: "Shed No 50",
      //   Quantity: "32.000",
      //   MRP: null,
      //   Rate: "65.00",
      //   TaxType: "GST",
      //   UnitName: "Kg",
      //   BaseUnitQuantity: "78.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "104.00",
      //   InwardQuantity: "52.00",
      //   SGST: "52.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2184.00",
      //   OutQuantity: "550",
      //   BatchDate: "2023-01-18"
      // },
      // {
      //   Item: 61,
      //   Particulars: "Shed No 50",
      //   Quantity: "32.000",
      //   MRP: null,
      //   Rate: "65.00",
      //   TaxType: "GST",
      //   UnitName: "Kg",
      //   BaseUnitQuantity: "78.000",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "cash transactions",
      //   GSTBalance: "104.00",
      //   InwardQuantity: "52.00",
      //   SGST: "52.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "2184.00",
      //   OutQuantity: "550",
      //   BatchDate: "2023-01-18"
      // },{
      //   Item: 44,
      //   Particulars: "Shed No 44",
      //   Quantity: "cash transactions",
      //   MRP: null,
      //   Rate: "100.00",
      //   TaxType: "GST",
      //   UnitName: "No",
      //   BaseUnitQuantity: "cash transactions",
      //   GSTPercentage: "5.00",
      //   MarginValue: null,
      //   TransactionType: "200.00",
      //   GSTBalance: "10.00",
      //   InwardQuantity: "5.00",
      //   SGST: "5.00",
      //   IGST: "0.00",
      //  InQuantity: "2.50",
      //   SGSTPercentage: "2.50",
      //  IssueQuanity: "0.00",
      //   Balance: "210.00",
      //   OutQuantity: "0",
      //   BatchDate: "2023-01-21"
      // },
      
     
      
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "5456",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "30.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "150.00",
        InwardQuantity: "75.00",
        SGST: "75.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "3150.00",
        OutQuantity: "65",
        BatchDate: "2023-01-18"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "10.500",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "10.500",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "28.88",
        InwardQuantity: "14.44",
        SGST: "14.44",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "606.38",
        OutQuantity: "12",
        BatchDate: "2023-01-10"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "6.000",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "11.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "16.50",
        InwardQuantity: "8.25",
        SGST: "8.25",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "346.50",
        OutQuantity: "0",
        BatchDate: "2023-01-18"
      },
      {
        Item: 61,
        Particulars: "Shed No 50",
        Quantity: "32.000",
        MRP: null,
        Rate: "65.00",
        TaxType: "GST",
        UnitName: "Kg",
        BaseUnitQuantity: "78.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "104.00",
        InwardQuantity: "52.00",
        SGST: "52.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2184.00",
        OutQuantity: "550",
        BatchDate: "2023-01-18"
      },
      {
        Item: 44,
        Particulars: "Shed No 44",
        Quantity: "cash transactions",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "cash transactions",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "200.00",
        GSTBalance: "10.00",
        InwardQuantity: "5.00",
        SGST: "5.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "210.00",
        OutQuantity: "0",
        BatchDate: "2023-01-21"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "20.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "20.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "100.00",
        InwardQuantity: "50.00",
        SGST: "50.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2100.00",
        OutQuantity: "45",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "4454",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "04525",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "5456",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "30.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "150.00",
        InwardQuantity: "75.00",
        SGST: "75.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "3150.00",
        OutQuantity: "65",
        BatchDate: "2023-01-18"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "10.500",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "10.500",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "28.88",
        InwardQuantity: "14.44",
        SGST: "14.44",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "606.38",
        OutQuantity: "12",
        BatchDate: "2023-01-10"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "6.000",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "11.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "16.50",
        InwardQuantity: "8.25",
        SGST: "8.25",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "346.50",
        OutQuantity: "0",
        BatchDate: "2023-01-18"
      },
      {
        Item: 61,
        Particulars: "Shed No 50",
        Quantity: "32.000",
        MRP: null,
        Rate: "65.00",
        TaxType: "GST",
        UnitName: "Kg",
        BaseUnitQuantity: "78.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "104.00",
        InwardQuantity: "52.00",
        SGST: "52.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2184.00",
        OutQuantity: "550",
        BatchDate: "2023-01-18"
      },
      {
        Item: 61,
        Particulars: "Shed No 50",
        Quantity: "32.000",
        MRP: null,
        Rate: "65.00",
        TaxType: "GST",
        UnitName: "Kg",
        BaseUnitQuantity: "78.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "104.00",
        InwardQuantity: "52.00",
        SGST: "52.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2184.00",
        OutQuantity: "550",
        BatchDate: "2023-01-18"
      },{
        Item: 44,
        Particulars: "Shed No 44",
        Quantity: "cash transactions",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "cash transactions",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "200.00",
        GSTBalance: "10.00",
        InwardQuantity: "5.00",
        SGST: "5.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "210.00",
        OutQuantity: "0",
        BatchDate: "2023-01-21"
      },
      
     
      
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "5456",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "30.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "150.00",
        InwardQuantity: "75.00",
        SGST: "75.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "3150.00",
        OutQuantity: "65",
        BatchDate: "2023-01-18"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "10.500",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "10.500",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "28.88",
        InwardQuantity: "14.44",
        SGST: "14.44",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "606.38",
        OutQuantity: "12",
        BatchDate: "2023-01-10"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "6.000",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "11.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "16.50",
        InwardQuantity: "8.25",
        SGST: "8.25",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "346.50",
        OutQuantity: "0",
        BatchDate: "2023-01-18"
      },
      {
        Item: 61,
        Particulars: "Shed No 50",
        Quantity: "32.000",
        MRP: null,
        Rate: "65.00",
        TaxType: "GST",
        UnitName: "Kg",
        BaseUnitQuantity: "78.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "104.00",
        InwardQuantity: "52.00",
        SGST: "52.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2184.00",
        OutQuantity: "550",
        BatchDate: "2023-01-18"
      },
      {
        Item: 44,
        Particulars: "Shed No 44",
        Quantity: "cash transactions",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "cash transactions",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "200.00",
        GSTBalance: "10.00",
        InwardQuantity: "5.00",
        SGST: "5.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "210.00",
        OutQuantity: "0",
        BatchDate: "2023-01-21"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "20.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "20.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "100.00",
        InwardQuantity: "50.00",
        SGST: "50.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2100.00",
        OutQuantity: "45",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "4454",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "04525",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "5456",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "100.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "credit transactions",
        GSTBalance: "500.00",
        InwardQuantity: "250.00",
        SGST: "250.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "10500.00",
        OutQuantity: "566",
        BatchDate: "2023-01-18"
      },
      {
        Item: 46,
        Particulars: "Shed No 50",
        Quantity: "30.000",
        MRP: null,
        Rate: "100.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "100.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "150.00",
        InwardQuantity: "75.00",
        SGST: "75.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "3150.00",
        OutQuantity: "65",
        BatchDate: "2023-01-18"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "10.500",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "10.500",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "28.88",
        InwardQuantity: "14.44",
        SGST: "14.44",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "606.38",
        OutQuantity: "12",
        BatchDate: "2023-01-10"
      },
      {
        Item: 60,
        Particulars: "Shed No 50",
        Quantity: "6.000",
        MRP: null,
        Rate: "55.00",
        TaxType: "GST",
        UnitName: "No",
        BaseUnitQuantity: "11.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "16.50",
        InwardQuantity: "8.25",
        SGST: "8.25",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "346.50",
        OutQuantity: "0",
        BatchDate: "2023-01-18"
      },
      {
        Item: 61,
        Particulars: "Shed No 50",
        Quantity: "32.000",
        MRP: null,
        Rate: "65.00",
        TaxType: "GST",
        UnitName: "Kg",
        BaseUnitQuantity: "78.000",
        GSTPercentage: "5.00",
        MarginValue: null,
        TransactionType: "cash transactions",
        GSTBalance: "104.00",
        InwardQuantity: "52.00",
        SGST: "52.00",
        IGST: "0.00",
       InQuantity: "2.50",
        SGSTPercentage: "2.50",
       IssueQuanity: "0.00",
        Balance: "2184.00",
        OutQuantity: "550",
        BatchDate: "2023-01-18"
      }
    ]
  }