function initialdata(orderid) {
    return {
        "OrderIDs": [
            orderid
        ],
        "OrderItemDetails": [
            {
                "id": 172386,
                "Item": 81,
                "ItemName": "Khatta Meetha Mixture 150 g",
                "Quantity": "7.000",
                "MRP": 774,
                "MRPValue": "65.00",
                "Rate": "45.96",
                "Unit": 548,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "7.000",
                "GST": 81,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "321.72",
                "GSTAmount": "38.60",
                "CGST": "19.30",
                "SGST": "19.30",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "360.32",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 548,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 45.96,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 549,
                        "UnitName": "Kg (6.666 No)",
                        "BaseUnitQuantity": "6.666",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 45.96,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 550,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 45.96,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 216253,
                        "Item": 81,
                        "BatchDate": "2023-12-06",
                        "BatchCode": "06L23SN3",
                        "SystemBatchDate": "2023-12-22",
                        "SystemBatchCode": "20231222_81_15_0",
                        "LiveBatche": 74249,
                        "LiveBatcheMRPID": 774,
                        "LiveBatcheGSTID": 81,
                        "Rate": 45.96,
                        "MRP": "65.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 172387,
                "Item": 82,
                "ItemName": "Lasoon Shev 150 g",
                "Quantity": "10.000",
                "MRP": 775,
                "MRPValue": "65.00",
                "Rate": "45.96",
                "Unit": 247,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "10.000",
                "GST": 82,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "459.60",
                "GSTAmount": "55.16",
                "CGST": "27.58",
                "SGST": "27.58",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "514.76",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 247,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 45.96,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 248,
                        "UnitName": "Kg (6.666 No)",
                        "BaseUnitQuantity": "6.666",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 45.96,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 249,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 45.96,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 216254,
                        "Item": 82,
                        "BatchDate": "2023-12-11",
                        "BatchCode": "11L23SN4",
                        "SystemBatchDate": "2023-12-22",
                        "SystemBatchCode": "20231222_82_15_0",
                        "LiveBatche": 74250,
                        "LiveBatcheMRPID": 775,
                        "LiveBatcheGSTID": 82,
                        "Rate": 45.96,
                        "MRP": "65.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 172388,
                "Item": 83,
                "ItemName": "Navratan Mix 150 g",
                "Quantity": "7.000",
                "MRP": 776,
                "MRPValue": "70.00",
                "Rate": "49.50",
                "Unit": 250,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "7.000",
                "GST": 83,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "346.50",
                "GSTAmount": "41.58",
                "CGST": "20.79",
                "SGST": "20.79",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "388.08",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 250,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 49.5,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 251,
                        "UnitName": "Kg (6.666 No)",
                        "BaseUnitQuantity": "6.666",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 49.5,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 252,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 49.5,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 216255,
                        "Item": 83,
                        "BatchDate": "2023-11-22",
                        "BatchCode": "22K23SN1",
                        "SystemBatchDate": "2023-12-22",
                        "SystemBatchCode": "20231222_83_15_0",
                        "LiveBatche": 74251,
                        "LiveBatcheMRPID": 776,
                        "LiveBatcheGSTID": 83,
                        "Rate": 49.5,
                        "MRP": "70.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 172384,
                "Item": 101,
                "ItemName": "Lite Chivda 200 g",
                "Quantity": "9.000",
                "MRP": 721,
                "MRPValue": "75.00",
                "Rate": "53.04",
                "Unit": 307,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "9.000",
                "GST": 101,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "477.36",
                "GSTAmount": "57.28",
                "CGST": "28.64",
                "SGST": "28.64",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "534.64",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 307,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 308,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 309,
                        "UnitName": "Box (25 No)",
                        "BaseUnitQuantity": "25.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 204899,
                        "Item": 101,
                        "BatchDate": "2023-11-01",
                        "BatchCode": "01PK2023",
                        "SystemBatchDate": "2023-12-08",
                        "SystemBatchCode": "20231208_101_15_0",
                        "LiveBatche": 62895,
                        "LiveBatcheMRPID": 721,
                        "LiveBatcheGSTID": 101,
                        "Rate": 53.04,
                        "MRP": "75.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "75.000"
                    }
                ]
            },
            {
                "id": 172385,
                "Item": 104,
                "ItemName": "Patal Poha Chivda 200 g",
                "Quantity": "5.000",
                "MRP": 724,
                "MRPValue": "75.00",
                "Rate": "53.04",
                "Unit": 316,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "5.000",
                "GST": 104,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "265.20",
                "GSTAmount": "31.82",
                "CGST": "15.91",
                "SGST": "15.91",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "297.02",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 316,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 317,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 318,
                        "UnitName": "Box (25 No)",
                        "BaseUnitQuantity": "25.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 207813,
                        "Item": 104,
                        "BatchDate": "2023-11-19",
                        "BatchCode": "19PK2023",
                        "SystemBatchDate": "2023-12-11",
                        "SystemBatchCode": "20231211_104_15_0",
                        "LiveBatche": 65809,
                        "LiveBatcheMRPID": 724,
                        "LiveBatcheGSTID": 104,
                        "Rate": 53.04,
                        "MRP": "75.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "25.000"
                    }
                ]
            },
            {
                "id": 172383,
                "Item": 125,
                "ItemName": "Khari Bundi 200 g",
                "Quantity": "8.000",
                "MRP": 745,
                "MRPValue": "72.00",
                "Rate": "50.92",
                "Unit": 379,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "8.000",
                "GST": 125,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "407.36",
                "GSTAmount": "48.88",
                "CGST": "24.44",
                "SGST": "24.44",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "456.24",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 379,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 50.92,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 380,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 50.92,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 381,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 50.92,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 216259,
                        "Item": 125,
                        "BatchDate": "2023-12-07",
                        "BatchCode": "07PL2023",
                        "SystemBatchDate": "2023-12-22",
                        "SystemBatchCode": "20231222_125_15_0",
                        "LiveBatche": 74255,
                        "LiveBatcheMRPID": 745,
                        "LiveBatcheGSTID": 125,
                        "Rate": 50.92,
                        "MRP": "72.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 172389,
                "Item": 151,
                "ItemName": "Aloo Bhujiya 150 g",
                "Quantity": "5.000",
                "MRP": 779,
                "MRPValue": "75.00",
                "Rate": "53.04",
                "Unit": 563,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "5.000",
                "GST": 152,
                "HSNCode": "21069099",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "265.20",
                "GSTAmount": "31.82",
                "CGST": "15.91",
                "SGST": "15.91",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "297.02",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 563,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 564,
                        "UnitName": "Kg (6.667 No)",
                        "BaseUnitQuantity": "6.667",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 565,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 53.04,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 216261,
                        "Item": 151,
                        "BatchDate": "2023-12-07",
                        "BatchCode": "07L23SN6",
                        "SystemBatchDate": "2023-12-22",
                        "SystemBatchCode": "20231222_151_15_0",
                        "LiveBatche": 74257,
                        "LiveBatcheMRPID": 779,
                        "LiveBatcheGSTID": 152,
                        "Rate": 53.04,
                        "MRP": "75.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 172382,
                "Item": 166,
                "ItemName": "Soanpapdi Classic 200g",
                "Quantity": "16.000",
                "MRP": 809,
                "MRPValue": "80.00",
                "Rate": "60.34",
                "Unit": 622,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "16.000",
                "GST": 167,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "965.44",
                "GSTAmount": "48.28",
                "CGST": "24.14",
                "SGST": "24.14",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "1013.72",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 622,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 623,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 624,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 216262,
                        "Item": 166,
                        "BatchDate": "2023-12-08",
                        "BatchCode": "08RLD2023",
                        "SystemBatchDate": "2023-12-22",
                        "SystemBatchCode": "20231222_166_15_0",
                        "LiveBatche": 74258,
                        "LiveBatcheMRPID": 809,
                        "LiveBatcheGSTID": 167,
                        "Rate": 60.34,
                        "MRP": "80.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "25.000"
                    },
                    {
                        "id": 225478,
                        "Item": 166,
                        "BatchDate": "2023-12-26",
                        "BatchCode": "26RL2023",
                        "SystemBatchDate": "2023-12-31",
                        "SystemBatchCode": "20231231_166_15_0",
                        "LiveBatche": 83474,
                        "LiveBatcheMRPID": 809,
                        "LiveBatcheGSTID": 167,
                        "Rate": 60.34,
                        "MRP": "80.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "300.000"
                    }
                ]
            },
            {
                "id": 172380,
                "Item": 167,
                "ItemName": "Soanpapdi Classic Mango 200 g",
                "Quantity": "28.000",
                "MRP": 810,
                "MRPValue": "80.00",
                "Rate": "60.34",
                "Unit": 625,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "28.000",
                "GST": 168,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "1689.52",
                "GSTAmount": "84.48",
                "CGST": "42.24",
                "SGST": "42.24",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "1774.00",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 625,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 626,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 627,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 225479,
                        "Item": 167,
                        "BatchDate": "2023-12-27",
                        "BatchCode": "27RL2023",
                        "SystemBatchDate": "2023-12-31",
                        "SystemBatchCode": "20231231_167_15_0",
                        "LiveBatche": 83475,
                        "LiveBatcheMRPID": 810,
                        "LiveBatcheGSTID": 168,
                        "Rate": 60.34,
                        "MRP": "80.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "289.000"
                    }
                ]
            },
            {
                "id": 172381,
                "Item": 168,
                "ItemName": "Soanpapdi Classic Orange 200 g",
                "Quantity": "1.000",
                "MRP": 811,
                "MRPValue": "80.00",
                "Rate": "1206.80",
                "Unit": 630,
                "UnitName": "Box (20 No)",
                "DeletedMCUnitsUnitID": 4,
                "ConversionUnit": "20.000",
                "BaseUnitQuantity": "20.000",
                "GST": 169,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "1206.80",
                "GSTAmount": "60.34",
                "CGST": "30.17",
                "SGST": "30.17",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "1267.14",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 628,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 629,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 630,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 60.34,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 186879,
                        "Item": 168,
                        "BatchDate": "2023-11-05",
                        "BatchCode": "05RKD2023",
                        "SystemBatchDate": "2023-11-08",
                        "SystemBatchCode": "20231108_168_15_0",
                        "LiveBatche": 44875,
                        "LiveBatcheMRPID": 811,
                        "LiveBatcheGSTID": 169,
                        "Rate": 60.34,
                        "MRP": "80.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "97.000"
                    },
                    {
                        "id": 225480,
                        "Item": 168,
                        "BatchDate": "2023-12-21",
                        "BatchCode": "21RL2023",
                        "SystemBatchDate": "2023-12-31",
                        "SystemBatchCode": "20231231_168_15_0",
                        "LiveBatche": 83476,
                        "LiveBatcheMRPID": 811,
                        "LiveBatcheGSTID": 169,
                        "Rate": 60.34,
                        "MRP": "80.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "180.000"
                    }
                ]
            }
        ]
    }
}
function initial(orderid) {
    return {
        "OrderIDs": [
            orderid
        ],
        "OrderItemDetails": [
            {
                "id": 171460,
                "Item": 1,
                "ItemName": "Mango Burfi 250 g",
                "Quantity": "1.000",
                "MRP": 781,
                "MRPValue": "235.00",
                "Rate": "198.06",
                "Unit": 1,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "1.000",
                "GST": 151,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "198.06",
                "GSTAmount": "9.90",
                "CGST": "4.95",
                "SGST": "4.95",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "207.96",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 1,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 198.06,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 2,
                        "UnitName": "Kg (4 No)",
                        "BaseUnitQuantity": "4.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 198.06,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 3,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 198.06,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 231466,
                        "Item": 1,
                        "BatchDate": "2024-01-03",
                        "BatchCode": "03RA2024",
                        "SystemBatchDate": "2024-01-03",
                        "SystemBatchCode": "20240103_1_6_0",
                        "LiveBatche": 89462,
                        "LiveBatcheMRPID": 781,
                        "LiveBatcheGSTID": 151,
                        "Rate": 198.06,
                        "MRP": "235.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "40.000"
                    }
                ]
            },
            {
                "id": 171458,
                "Item": 45,
                "ItemName": "Kaju Katali 250 g",
                "Quantity": "1.000",
                "MRP": 665,
                "MRPValue": "265.00",
                "Rate": "219.46",
                "Unit": 133,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "1.000",
                "GST": 45,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "219.46",
                "GSTAmount": "10.98",
                "CGST": "5.49",
                "SGST": "5.49",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "230.44",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 133,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 219.46,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 134,
                        "UnitName": "Kg (4 No)",
                        "BaseUnitQuantity": "4.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 219.46,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 135,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 219.46,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 231474,
                        "Item": 45,
                        "BatchDate": "2024-01-02",
                        "BatchCode": "02RA2024",
                        "SystemBatchDate": "2024-01-03",
                        "SystemBatchCode": "20240103_45_6_0",
                        "LiveBatche": 89470,
                        "LiveBatcheMRPID": 665,
                        "LiveBatcheGSTID": 45,
                        "Rate": 219.46,
                        "MRP": "265.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "140.000"
                    }
                ]
            },
            {
                "id": 171459,
                "Item": 86,
                "ItemName": "Sadha Pedha 200 g",
                "Quantity": "1.000",
                "MRP": 706,
                "MRPValue": "170.00",
                "Rate": "140.79",
                "Unit": 262,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "1.000",
                "GST": 86,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "140.79",
                "GSTAmount": "7.04",
                "CGST": "3.52",
                "SGST": "3.52",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "147.83",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 262,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 140.79,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 263,
                        "UnitName": "Kg (5 No)",
                        "BaseUnitQuantity": "5.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 140.79,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 264,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 140.79,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": []
            }
        ]
    }
}
function  initial2(orderid){
    return {
        "OrderIDs": [
            orderid
        ],
        "OrderItemDetails": [
            {
                "id": 188050,
                "Item": 13,
                "ItemName": "Banana Chips Spicy Masala 125 g",
                "Quantity": "1.000",
                "MRP": 633,
                "MRPValue": "60.00",
                "Rate": "1357.76",
                "Unit": 40,
                "UnitName": "Box (32 No)",
                "DeletedMCUnitsUnitID": 4,
                "ConversionUnit": "32.000",
                "BaseUnitQuantity": "32.000",
                "GST": 220,
                "HSNCode": "20089999",
                "GSTPercentage": "12.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "1357.76",
                "GSTAmount": "162.94",
                "CGST": "81.47",
                "SGST": "81.47",
                "IGST": "0.00",
                "CGSTPercentage": "6.00",
                "SGSTPercentage": "6.00",
                "IGSTPercentage": "0.00",
                "Amount": "1520.70",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 38,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 42.43,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 39,
                        "UnitName": "Kg (8 No)",
                        "BaseUnitQuantity": "8.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 42.43,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 40,
                        "UnitName": "Box (32 No)",
                        "BaseUnitQuantity": "32.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 42.43,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 234176,
                        "Item": 13,
                        "BatchDate": "2023-12-25",
                        "BatchCode": "25L23SC1",
                        "SystemBatchDate": "2024-01-04",
                        "SystemBatchCode": "20240104_13_19_0",
                        "LiveBatche": 92172,
                        "LiveBatcheMRPID": 633,
                        "LiveBatcheGSTID": 220,
                        "Rate": 42.43,
                        "MRP": "60.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "95.000"
                    },
                    {
                        "id": 238201,
                        "Item": 13,
                        "BatchDate": "2023-12-25",
                        "BatchCode": "25L23SC1",
                        "SystemBatchDate": "2024-01-08",
                        "SystemBatchCode": "20240108_13_19_0",
                        "LiveBatche": 96197,
                        "LiveBatcheMRPID": 633,
                        "LiveBatcheGSTID": 220,
                        "Rate": 42.43,
                        "MRP": "60.00",
                        "GST": "12.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "128.000"
                    }
                ]
            },
            {
                "id": 188051,
                "Item": 50,
                "ItemName": "Besan Ladoo 250 g",
                "Quantity": "5.000",
                "MRP": 670,
                "MRPValue": "140.00",
                "Rate": "108.36",
                "Unit": 148,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "5.000",
                "GST": 50,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "541.80",
                "GSTAmount": "27.08",
                "CGST": "13.54",
                "SGST": "13.54",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "568.88",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 148,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 108.36,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 149,
                        "UnitName": "Kg (4 No)",
                        "BaseUnitQuantity": "4.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 108.36,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 150,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 108.36,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 214254,
                        "Item": 50,
                        "BatchDate": "2023-12-14",
                        "BatchCode": "14RL2023",
                        "SystemBatchDate": "2023-12-18",
                        "SystemBatchCode": "20231218_50_19_0",
                        "LiveBatche": 72250,
                        "LiveBatcheMRPID": 670,
                        "LiveBatcheGSTID": 50,
                        "Rate": 108.36,
                        "MRP": "140.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000"
                    },
                    {
                        "id": 222670,
                        "Item": 50,
                        "BatchDate": "2023-12-17",
                        "BatchCode": "17RL2023",
                        "SystemBatchDate": "2023-12-28",
                        "SystemBatchCode": "20231228_50_19_0",
                        "LiveBatche": 80666,
                        "LiveBatcheMRPID": 670,
                        "LiveBatcheGSTID": 50,
                        "Rate": 108.36,
                        "MRP": "140.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 188052,
                "Item": 51,
                "ItemName": "Dink Ladoo 250 g",
                "Quantity": "5.000",
                "MRP": 671,
                "MRPValue": "150.00",
                "Rate": "116.10",
                "Unit": 151,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "5.000",
                "GST": 51,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "580.50",
                "GSTAmount": "29.02",
                "CGST": "14.51",
                "SGST": "14.51",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "609.52",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 151,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 116.1,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 152,
                        "UnitName": "Kg (4 No)",
                        "BaseUnitQuantity": "4.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 116.1,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 153,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 116.1,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 215970,
                        "Item": 51,
                        "BatchDate": "2023-12-15",
                        "BatchCode": "15RL2023",
                        "SystemBatchDate": "2023-12-21",
                        "SystemBatchCode": "20231221_51_19_0",
                        "LiveBatche": 73966,
                        "LiveBatcheMRPID": 671,
                        "LiveBatcheGSTID": 51,
                        "Rate": 116.1,
                        "MRP": "150.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "6.000"
                    },
                    {
                        "id": 222671,
                        "Item": 51,
                        "BatchDate": "2023-12-26",
                        "BatchCode": "26RL2023",
                        "SystemBatchDate": "2023-12-28",
                        "SystemBatchCode": "20231228_51_19_0",
                        "LiveBatche": 80667,
                        "LiveBatcheMRPID": 671,
                        "LiveBatcheGSTID": 51,
                        "Rate": 116.1,
                        "MRP": "150.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    },
                    {
                        "id": 234180,
                        "Item": 51,
                        "BatchDate": "2023-12-26",
                        "BatchCode": "26RL2023",
                        "SystemBatchDate": "2024-01-04",
                        "SystemBatchCode": "20240104_51_19_0",
                        "LiveBatche": 92176,
                        "LiveBatcheMRPID": 671,
                        "LiveBatcheGSTID": 51,
                        "Rate": 116.1,
                        "MRP": "150.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 188053,
                "Item": 52,
                "ItemName": "Methi Ladoo 250 g",
                "Quantity": "5.000",
                "MRP": 672,
                "MRPValue": "170.00",
                "Rate": "131.58",
                "Unit": 154,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "5.000",
                "GST": 52,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "657.90",
                "GSTAmount": "32.90",
                "CGST": "16.45",
                "SGST": "16.45",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "690.80",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 154,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 131.58,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 155,
                        "UnitName": "Kg (4 No)",
                        "BaseUnitQuantity": "4.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 131.58,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 156,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 131.58,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 215971,
                        "Item": 52,
                        "BatchDate": "2023-12-15",
                        "BatchCode": "15RL2023",
                        "SystemBatchDate": "2023-12-21",
                        "SystemBatchCode": "20231221_52_19_0",
                        "LiveBatche": 73967,
                        "LiveBatcheMRPID": 672,
                        "LiveBatcheGSTID": 52,
                        "Rate": 131.58,
                        "MRP": "170.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "5.000"
                    },
                    {
                        "id": 234181,
                        "Item": 52,
                        "BatchDate": "2023-12-27",
                        "BatchCode": "27RL2023",
                        "SystemBatchDate": "2024-01-04",
                        "SystemBatchCode": "20240104_52_19_0",
                        "LiveBatche": 92177,
                        "LiveBatcheMRPID": 672,
                        "LiveBatcheGSTID": 52,
                        "Rate": 131.58,
                        "MRP": "170.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "20.000"
                    }
                ]
            },
            {
                "id": 188054,
                "Item": 53,
                "ItemName": "Motichoor Ladoo 250 g Pack",
                "Quantity": "5.000",
                "MRP": 975,
                "MRPValue": "160.00",
                "Rate": "123.84",
                "Unit": 157,
                "UnitName": "No",
                "DeletedMCUnitsUnitID": 1,
                "ConversionUnit": "1.000",
                "BaseUnitQuantity": "5.000",
                "GST": 53,
                "HSNCode": "21069099",
                "GSTPercentage": "5.00",
                "Margin": null,
                "MarginValue": null,
                "BasicAmount": "619.20",
                "GSTAmount": "30.96",
                "CGST": "15.48",
                "SGST": "15.48",
                "IGST": "0.00",
                "CGSTPercentage": "2.50",
                "SGSTPercentage": "2.50",
                "IGSTPercentage": "0.00",
                "Amount": "650.16",
                "DiscountType": "",
                "Discount": "",
                "UnitDetails": [
                    {
                        "UnitID": 157,
                        "UnitName": "No",
                        "BaseUnitQuantity": "1.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": true,
                        "Rate": 123.84,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 1
                    },
                    {
                        "UnitID": 158,
                        "UnitName": "Kg (4 No)",
                        "BaseUnitQuantity": "4.000",
                        "PODefaultUnit": false,
                        "SODefaultUnit": false,
                        "Rate": 123.84,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 2
                    },
                    {
                        "UnitID": 159,
                        "UnitName": "Box (20 No)",
                        "BaseUnitQuantity": "20.000",
                        "PODefaultUnit": true,
                        "SODefaultUnit": false,
                        "Rate": 123.84,
                        "BaseUnitQuantityNoUnit": "1.000",
                        "DeletedMCUnitsUnitID": 4
                    }
                ],
                "StockDetails": [
                    {
                        "id": 234182,
                        "Item": 53,
                        "BatchDate": "2023-12-23",
                        "BatchCode": "23RL2023",
                        "SystemBatchDate": "2024-01-04",
                        "SystemBatchCode": "20240104_53_19_0",
                        "LiveBatche": 92178,
                        "LiveBatcheMRPID": 975,
                        "LiveBatcheGSTID": 53,
                        "Rate": 123.84,
                        "MRP": "160.00",
                        "GST": "5.00",
                        "UnitName": "No",
                        "BaseUnitQuantity": "11.000"
                    }
                ]
            }
        ]
    }
}
const start = 1;
const end = 21;
const bulkdata = [];

for (let i = start; i < end; i++) {
    // bulkdata.push(initialdata(i));
    bulkdata.push(initial2(i));
}

export default bulkdata