// export const GET_ORDER_ITEMS_FOR_ORDER_PAGE = "GET_ORDER_ITEMS_FOR_ORDER_PAGE"
// export const GET_ORDER_ITEMS_FOR_ORDER_PAGE_SUCCESS = 'GET_ORDER_ITEMS_FOR_ORDER_PAGE_SUCCESS'

export const POST_CREDITLIMIT_PAGE = 'POST_CREDITLIMIT_PAGE'
export const POST_CREDITLIMIT_PAGE_SUCCESS = 'POST_CREDITLIMIT_PAGE_SUCCESS'

// export const GET_ORDER_LIST = 'GET_ORDER_LIST'
// export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'


// export const EDIT_ORDER_FOR_ORDER_PAGE = 'EDIT_ORDER_FOR_ORDER_PAGE'
// export const EDIT_ORDER_FOR_ORDER_PAGE_SUCCESS = 'EDIT_ORDER_FOR_ORDER_PAGE_SUCCESS'

export const GET_ROUTESDROPDOWN = 'GET_ROUTESDROPDOWN'
export const GET_ROUTESDROPDOWN_SUCCESS = 'GET_ROUTESDROPDOWN_SUCCESS'

// export const UPDATE_ORDER_ID_FROM_ORDER_PAGE = 'UPDATE_ORDER_ID_FROM_ORDER_PAGE'
// export const UPDATE_ORDER_ID_FROM_ORDER_PAGE_SUCCESS = 'UPDATE_ORDER_ID_FROM_ORDER_PAGE_SUCCESS'


export const GO_BUTTON_FOR_CREDITLIMIT_PAGE = 'GO_BUTTON_FOR_CREDITLIMIT_PAGE'
export const GO_BUTTON_FOR_CREDITLIMIT_PAGE_SUCCESS = 'GO_BUTTON_FOR_CREDITLIMIT_PAGE_SUCCESS'

// export const GET_ORDER_LIST_PAGE = 'GET_ORDER_LIST_PAGE'
// export const GET_ORDER_LIST_PAGE_SUCCESS = 'GET_ORDER_LIST_PAGE_SUCCESS'

// export const ORDER_LIST_FILTERS = 'ORDER_LIST_FILTERS'



