// Submit Module  All Action type

export const  PAGE_MASTER_ACCESS_FOR_ROLE_ACCESS_lIST='PAGE_MASTER_ACCESS_FOR_ROLE_ACCESS_lIST'
export const  PAGE_MASTER_ACCESS_FOR_ROLE_ACCESS_lIST_SUCCESS='PAGE_MASTER_ACCESS_FOR_ROLE_ACCESS_lIST_SUCCESS'

