export const POST_PARTYITEMS = "POST_PARTYITEMS"
export const POST_PARTYITEMS_SUCCESS = "POST_PARTYITEMS_SUCCESS"

export const GET_PARTY_LIST = "GET_PARTY_LIST"
export const GET_PARTY_LIST_SUCCESS = 'GET_PARTY_LIST_SUCCESS'

export const GET_PARTY_ITEM_LIST = 'GET_PARTY_ITEM_LIST'
export const GET_PARTY_ITEM_LIST_SUCCESS = 'GET_PARTY_ITEM_LIST_SUCCESS'

export const EDIT_PARTY_ITEM_ID = 'EDIT_PARTY_ITEM_ID'
export const EDIT_PARTY_ITEM_ID_SUCCESS = 'EDIT_PARTY_ITEM_ID_SUCCESS'

export const PARTY_ITEM_API_ERROR_ACTION = 'PARTY_ITEM_API_ERROR_ACTION'




