export const InvoiceFakeData = {
    
  "InvoiceID": 154245,
  "InvoiceDate": "2022-04-13T00:00:00",
  "GSTIN": "27ABDPG6424C1Z4",
  "EWaYBill":"1524247514",
  "BilByName":"M/s.B.G.Chitale",
  "BilByAdr":"At post pune Ambegoa gjhgjkhgjkgjjkj Station Tal:Palus,Dist:Sangli",
  "BilByState":"Maharashtra (27)",
  "BilByGSTIN":"27AABFB3828J1ZH",
  "BilByFSSAI":"10012022000033",
  "BilToName":"Chaitanya Marketing",
  "BilToAdr":"D-4/5,Industrial Estete-Bicholim Goa",
  "BilToState":"GOA (30)",
  "BilToGSTIN":"30AABFB3828J1LK",
  "BilToFSSAI":"40012022000039",

  "GrandTotal": 12680.63,
  "InvoiceServiceItems": [
    {
      "InvoiceID":1,
      "InvoiceItemID": 2033135,
      "ItemID": 263,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.4,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
      "GSTPercentage":5.0,
      "GSTAmount": 151.0,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033135,
          "BatchCode": "202204135537-1",
          "BatchDate": " ",
          "Quantity": 12.8
        }
      ]
    },
    {
      "InvoiceID": 2,
      "InvoiceItemID": 2033135,
      "ItemID": 263,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.4,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 151.0,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033135,
          "BatchCode": "202204135537-1",
          "BatchDate": " ",
          "Quantity": 12.8
        }
      ]
    },
    {
      "InvoiceID": 3,
      "InvoiceItemID": 2033135,
      "ItemID": 263,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.4,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 151.0,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033135,
          "BatchCode": "202204135537-1",
          "BatchDate": " ",
          "Quantity": 12.8
        }
      ]
    },

    {
      "InvoiceID": 4,
      "InvoiceItemID": 2033135,
      "ItemID": 263,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.4,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 151.0,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033135,
          "BatchCode": "202204135537-1",
          "BatchDate": " ",
          "Quantity": 12.8
        }
      ]
    },
    
    {
      "InvoiceID": 5,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 5,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    {
      "InvoiceID": 6,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    {
      "InvoiceID": 7,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    {
      "InvoiceID": 8,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
      "GSTPercentage":.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 5.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
    
    {
      "InvoiceID": 9,
      "InvoiceItemID": 2033136,
      "ItemID": 267,
      "Quantity": 2.0,
      "UnitID": 1,
      "OrderUnit": 3,
      "BaseUnitQuantity": 6.0,
      "Rate": 5,
      "MRP": 0.0,
      "BasicAmount": 4,
      "TaxType": "GST",
         "GSTPercentage":5.0,
      "GSTAmount": 168.4,
      "Amount": 0.0,
      "CGST": 1,
      "SGST": 1,
      "IGST": 0.0,
      "CGSTPercentage": 2,
      "SGSTPercentage": 2,
      "IGSTPercentage": 0.0,
      "DiscountAmount": 0.0,
      "DiscountPercentage": 0.0,
      "Value": 3,
      "GSTPercent": 4.0,
      "PONumber": null,
      "MBatchCode": null,
      "MBatchDate": null,
      "InvoiceBatchcodeDetails": [
        {
          "InvoiceID": 228684,
          "InvoiceItemID": 2033136,
          "BatchCode": "202204135561-2",
          "BatchDate": " ",
          "Quantity": 12.0
        }
      ]
    },
     {
            "InvoiceID": 10,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": 11,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
           {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          
          {
            "InvoiceID": "12% last",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 12.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "18% First",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          }, {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "2033136",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "04901212 Full Cream Paesteurised Milk Dahi 200 g Pouch",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "04901212 Full Cream Shrikhand Badam Pista 250 gm",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": "18% Last",
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage": 18.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },       
          {
            "InvoiceID":1,
            "InvoiceItemID": 2033135,
            "ItemID": 263,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.4,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage":5.0,
            "GSTAmount": 151.0,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033135,
                "BatchCode": "202204135537-1",
                "BatchDate": " ",
                "Quantity": 12.8
              }
            ]
          },
          {
            "InvoiceID": 2,
            "InvoiceItemID": 2033135,
            "ItemID": 263,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.4,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 151.0,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033135,
                "BatchCode": "202204135537-1",
                "BatchDate": " ",
                "Quantity": 12.8
              }
            ]
          },
          {
            "InvoiceID": 3,
            "InvoiceItemID": 2033135,
            "ItemID": 263,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.4,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 151.0,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033135,
                "BatchCode": "202204135537-1",
                "BatchDate": " ",
                "Quantity": 12.8
              }
            ]
          },
      
          {
            "InvoiceID": 4,
            "InvoiceItemID": 2033135,
            "ItemID": 263,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.4,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 151.0,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033135,
                "BatchCode": "202204135537-1",
                "BatchDate": " ",
                "Quantity": 12.8
              }
            ]
          },
          
          {
            "InvoiceID": 5,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 5,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": 6,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": 7,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          {
            "InvoiceID": 8,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
            "GSTPercentage":.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 5.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
          
          {
            "InvoiceID": 9,
            "InvoiceItemID": 2033136,
            "ItemID": 267,
            "Quantity": 2.0,
            "UnitID": 1,
            "OrderUnit": 3,
            "BaseUnitQuantity": 6.0,
            "Rate": 5,
            "MRP": 0.0,
            "BasicAmount": 4,
            "TaxType": "GST",
               "GSTPercentage":5.0,
            "GSTAmount": 168.4,
            "Amount": 0.0,
            "CGST": 1,
            "SGST": 1,
            "IGST": 0.0,
            "CGSTPercentage": 2,
            "SGSTPercentage": 2,
            "IGSTPercentage": 0.0,
            "DiscountAmount": 0.0,
            "DiscountPercentage": 0.0,
            "Value": 3,
            "GSTPercent": 4.0,
            "PONumber": null,
            "MBatchCode": null,
            "MBatchDate": null,
            "InvoiceBatchcodeDetails": [
              {
                "InvoiceID": 228684,
                "InvoiceItemID": 2033136,
                "BatchCode": "202204135561-2",
                "BatchDate": " ",
                "Quantity": 12.0
              }
            ]
          },
           {
                  "InvoiceID": 10,
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                {
                  "InvoiceID": 11,
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                 {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                
                {
                  "InvoiceID": "12% last",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 12.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                {
                  "InvoiceID": "18% First",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 18.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                }, {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 18.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                {
                  "InvoiceID": "2033136",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 18.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                {
                  "InvoiceID": "04901212 Full Cream Paesteurised Milk Dahi 200 g Pouch",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 18.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                {
                  "InvoiceID": "04901212 Full Cream Shrikhand Badam Pista 250 gm",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 18.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },
                {
                  "InvoiceID": "18% Last",
                  "InvoiceItemID": 2033136,
                  "ItemID": 267,
                  "Quantity": 2.0,
                  "UnitID": 1,
                  "OrderUnit": 3,
                  "BaseUnitQuantity": 6.0,
                  "Rate": 5,
                  "MRP": 0.0,
                  "BasicAmount": 4,
                  "TaxType": "GST",
                  "GSTPercentage": 18.0,
                  "GSTAmount": 168.4,
                  "Amount": 0.0,
                  "CGST": 1,
                  "SGST": 1,
                  "IGST": 0.0,
                  "CGSTPercentage": 2,
                  "SGSTPercentage": 2,
                  "IGSTPercentage": 0.0,
                  "DiscountAmount": 0.0,
                  "DiscountPercentage": 0.0,
                  "Value": 3,
                  "GSTPercent": 5.0,
                  "PONumber": null,
                  "MBatchCode": null,
                  "MBatchDate": null,
                  "InvoiceBatchcodeDetails": [
                    {
                      "InvoiceID": 228684,
                      "InvoiceItemID": 2033136,
                      "BatchCode": "202204135561-2",
                      "BatchDate": " ",
                      "Quantity": 12.0
                    }
                  ]
                },       
         
  ]

}



