// get group items
export const GET_ITEM_GROUP_FOR_DROPDOWN="GET_ITEM_GROUP_FOR_DROPDOWN"
export const GET_ITEM_GROUP_FOR_DROPDOWN_SUCCESS="GET_ITEM_GROUP_FOR_DROPDOWN_SUCCESS"


// get api
export const GET_ITEM_LIST_API="GET_ITEM_LIST_API"
export const GET_ITEM_LIST_API_SUCCESS="GET_ITEM_LIST_API_SUCCESS"

// post api
export const POST_ITEM_DATA = "POST_ITEM_DATA"
export const POST_ITEM_DATA_SUCCESS = "POST_ITEM_DATA_SUCCESS"

// delete api
export const DELETE_ITEM_ID="DELETE_ITEM_ID"
export const DELETE_ITEM_ID_SUCCESS="DELETE_ITEM_ID_SUCCESS"

// edit api
export const EDIT_ITEM_ID="EDIT_ITEM_ID"
export const EDIT_ITEM_ID_SUCCESS="EDIT_ITEM_ID_SUCCESS"

// update api
export const UPDATE_ITEM_ID="UPDATE_ITEM_ID"
export const UPDATE_ITEM_ID_SUCCESS="UPDATE_ITEM_ID_SUCCESS"

// DropDown Api
export const GET_BASEUNIT_FOR_DROPDOWN="GET_BASEUNIT_FOR_DROPDOWN"
export const GET_BASEUNIT_FOR_DROPDOWN_SUCCESS="GET_BASEUNIT_FOR_DROPDOWN_SUCCESS"

export const GET_CATEGORYTYPE_FOR_DROPDOWN="GET_CATEGORYTYPE_FOR_DROPDOWN"
export const GET_CATEGORYTYPE_FOR_DROPDOWN_SUCCESS="GET_CATEGORYTYPE_FOR_DROPDOWN_SUCCESS"

export const GET_CATEGORY_FOR_DROPDOWN="GET_CATEGORY_FOR_DROPDOWN"
export const GET_CATEGORY_FOR_DROPDOWN_SUCCESS="GET_CATEGORY_FOR_DROPDOWN_SUCCESS"

export const GET_SUBCATEGORY_FOR_DROPDOWN="GET_SUBCATEGORY_FOR_DROPDOWN"
export const GET_SUBCATEGORY_FOR_DROPDOWN_SUCCESS="GET_SUBCATEGORY_FOR_DROPDOWN_SUCCESS"

export const GET_IMAGETYPE_FOR_DROPDOWN="GET_IMAGETYPE_FOR_DROPDOWN"
export const GET_IMAGETYPE_FOR_DROPDOWN_SUCCESS="GET_IMAGETYPE_FOR_DROPDOWN_SUCCESS"

export const GET_MRPTYPE_FOR_DROPDOWN="GET_MRPTYPE_FOR_DROPDOWN"
export const GET_MRPTYPE_FOR_DROPDOWN_SUCCESS="GET_MRPTYPE_FOR_DROPDOWN_SUCCESS"