export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN" 

export const ROLE_ACCESS_API_CALL='ROLE_ACCESS_API_CALL'
export const ROLE_ACCESS_API_CALL_SUCCESS='ROLE_ACCESS_API_CALL_SUCCESS'